export type MarkReady = (name: string) => void;
export type Get<T> = () => T;
export type Set<T> = (value: T) => void;
export type InvokeFn = (cmd: string, args?: Record<string, unknown>) => Promise<unknown>;
export type TimerHandle = ReturnType<typeof setTimeout> | null;

export type UiSaveSectionParams = {
  createUiSaveHelpers: (args: {
    invoke: InvokeFn;
    getUiConfigLoaded: Get<boolean>;
    getCurrentPath: Get<string>;
    getWindowBounds: Get<unknown>;
    getWindowBoundsReady: Get<boolean>;
    getShowHidden: Get<boolean>;
    getShowSize: Get<boolean>;
    getShowTime: Get<boolean>;
    getShowTree: Get<boolean>;
    getSortKey: Get<string>;
    getSortOrder: Get<string>;
    getPathHistory: Get<string[]>;
    getJumpList: Get<unknown[]>;
    getSearchHistory: Get<string[]>;
    getTheme: Get<"light" | "dark">;
    getUiSaveTimer: Get<TimerHandle>;
    setUiSaveTimer: Set<TimerHandle>;
    showError: (err: unknown) => void;
  }) => { saveUiStateNow: () => Promise<void>; scheduleUiSave: () => void };
  invoke: InvokeFn;
  getUiConfigLoaded: Get<boolean>;
  getCurrentPath: Get<string>;
  getWindowBounds: Get<unknown>;
  getWindowBoundsReady: Get<boolean>;
  getShowHidden: Get<boolean>;
  getShowSize: Get<boolean>;
  getShowTime: Get<boolean>;
  getShowTree: Get<boolean>;
  getSortKey: Get<string>;
  getSortOrder: Get<string>;
  getPathHistory: Get<string[]>;
  getJumpList: Get<unknown[]>;
  getSearchHistory: Get<string[]>;
  getTheme: Get<"light" | "dark">;
  getUiSaveTimer: Get<TimerHandle>;
  setUiSaveTimer: Set<TimerHandle>;
  showError: (err: unknown) => void;
  setSaveUiStateNow: Set<() => Promise<void>>;
  setScheduleUiSave: Set<() => void>;
  markReady: MarkReady;
};

export type KeymapSectionParams = {
  createKeymapHelpers: (args: {
    getKeymapProfile: Get<"windows" | "vim">;
    getKeymapCustom: Get<Record<string, string>>;
    setKeymapCustom: Set<Record<string, string>>;
    scheduleUiSave: () => void;
    KEYMAP_DEFAULTS: Record<string, unknown>;
    splitBindings: (value: string) => string[];
    normalizeKeyString: (value: string) => string;
    eventToKeyString: (event: KeyboardEvent) => string;
  }) => {
    getDefaultBinding: (action: string) => string;
    getCustomBinding: (action: string) => string;
    getActionBindings: (action: string) => string[];
    matchesAction: (event: KeyboardEvent, action: string) => boolean;
    setCustomBinding: (action: string, value: string) => void;
    resetCustomBinding: (action: string) => void;
    captureBinding: (event: KeyboardEvent) => string | null;
    getMenuShortcut: (action: string) => string;
  };
  getKeymapProfile: Get<"windows" | "vim">;
  getKeymapCustom: Get<Record<string, string>>;
  setKeymapCustom: Set<Record<string, string>>;
  getScheduleUiSave: Get<() => void>;
  KEYMAP_DEFAULTS: Record<string, unknown>;
  splitBindings: (value: string) => string[];
  normalizeKeyString: (value: string) => string;
  eventToKeyString: (event: KeyboardEvent) => string;
  setGetDefaultBinding: Set<(action: string) => string>;
  setGetCustomBinding: Set<(action: string) => string>;
  setGetActionBindings: Set<(action: string) => string[]>;
  setMatchesAction: Set<(event: KeyboardEvent, action: string) => boolean>;
  setSetCustomBinding: Set<(action: string, value: string) => void>;
  setResetCustomBinding: Set<(action: string) => void>;
  setCaptureBinding: Set<(event: KeyboardEvent) => string | null>;
  setGetMenuShortcut: Set<(action: string) => string>;
  markReady: MarkReady;
};

export type ListLayoutSectionParams = {
  createListLayoutHelpers: (args: {
    getListEl: Get<HTMLElement | null>;
    getListBodyEl: Get<HTMLElement | null>;
    getListCols: Get<number>;
    getListRows: Get<number>;
    getVisibleColStart: Get<number>;
    getVisibleColEnd: Get<number>;
    getFilteredCount: Get<number>;
    getShowSize: Get<boolean>;
    getShowTime: Get<boolean>;
    setListRows: Set<number>;
    setListCols: Set<number>;
    setNameMaxChars: Set<number>;
    setVisibleColStart: Set<number>;
    setVisibleColEnd: Set<number>;
    setOverflowLeft: Set<boolean>;
    setOverflowRight: Set<boolean>;
  }) => {
    updateListRows: () => void;
    updateOverflowMarkers: () => void;
    updateVisibleColumns: () => void;
    setScrollStartColumn: (startCol: number, rowsOverride?: number | null) => void;
    ensureColumnVisible: (targetCol: number, rowsOverride?: number | null) => void;
    scrollListHorizontallyByColumns: (deltaColumns: number) => void;
    getActualColumnSpan: (el: HTMLElement | null) => number;
  };
  getListEl: Get<HTMLElement | null>;
  getListBodyEl: Get<HTMLElement | null>;
  getListCols: Get<number>;
  getListRows: Get<number>;
  getVisibleColStart: Get<number>;
  getVisibleColEnd: Get<number>;
  getFilteredCount: Get<number>;
  getShowSize: Get<boolean>;
  getShowTime: Get<boolean>;
  setListRows: Set<number>;
  setListCols: Set<number>;
  setNameMaxChars: Set<number>;
  setVisibleColStart: Set<number>;
  setVisibleColEnd: Set<number>;
  setOverflowLeft: Set<boolean>;
  setOverflowRight: Set<boolean>;
  setUpdateListRows: Set<() => void>;
  setUpdateOverflowMarkers: Set<() => void>;
  setUpdateVisibleColumns: Set<() => void>;
  setSetScrollStartColumn: Set<(startCol: number, rowsOverride?: number | null) => void>;
  setEnsureColumnVisible: Set<(targetCol: number, rowsOverride?: number | null) => void>;
  setScrollListHorizontallyByColumns: Set<(deltaColumns: number) => void>;
  setGetActualColumnSpan: Set<(el: HTMLElement | null) => number>;
  markReady: MarkReady;
};

export type FocusSectionParams = {
  createFocusHelpers: (args: {
    getListEl: Get<HTMLElement | null>;
    getTreeEl: Get<HTMLElement | null>;
    getTreeBodyEl: Get<HTMLElement | null>;
    getTreeFocusedIndex: Get<number>;
    getTreeRoot: Get<unknown | null>;
    setTreeFocusedIndex: Set<number>;
    scrollTreeToFocus: (treeBodyEl: HTMLElement | null, focusedIndex: number) => void;
  }) => { focusList: () => void; focusTree: () => void; focusTreeTop: () => void };
  getListEl: Get<HTMLElement | null>;
  getTreeEl: Get<HTMLElement | null>;
  getTreeBodyEl: Get<HTMLElement | null>;
  getTreeFocusedIndex: Get<number>;
  getTreeRoot: Get<unknown | null>;
  setTreeFocusedIndex: Set<number>;
  scrollTreeToFocus: (treeBodyEl: HTMLElement | null, focusedIndex: number) => void;
  setFocusList: Set<() => void>;
  setFocusTree: Set<() => void>;
  setFocusTreeTop: Set<() => void>;
  markReady: MarkReady;
};

export type WatchSectionParams = {
  createWatchHelpers: (args: {
    invoke: InvokeFn;
    getWatchTimer: Get<TimerHandle>;
    setWatchTimer: Set<TimerHandle>;
  }) => { scheduleWatch: (path: string) => void };
  invoke: InvokeFn;
  getWatchTimer: Get<TimerHandle>;
  setWatchTimer: Set<TimerHandle>;
  setScheduleWatch: Set<(path: string) => void>;
  markReady: MarkReady;
};

export type TreeSectionParams = {
  createTreeHelpers: (args: {
    invoke: InvokeFn;
    getShowHidden: Get<boolean>;
    showError: (err: unknown) => void;
    createTreeNode: (...args: unknown[]) => unknown;
    isTreeListIgnorableError: (err: unknown) => boolean;
    autoExpandDepth: number;
    setTreeRoot: Set<unknown | null>;
    setTreeSelectedPath: Set<string>;
    setTreeFocusedIndex: Set<number>;
    getTreeBodyEl: Get<HTMLElement | null>;
    scrollTreeToFocus: (treeBodyEl: HTMLElement | null, focusedIndex: number) => void;
    getCurrentPath: Get<string>;
    getLoadDir: Get<(path: string) => Promise<void>>;
    setTreeLoading: Set<boolean>;
    handleTreeKeyUtil: (event: KeyboardEvent) => unknown;
    matchesAction: (event: KeyboardEvent, action: string) => boolean;
    getTreeFocusedIndex: Get<number>;
    getTreeEl: Get<HTMLElement | null>;
    getTreeRootSafe: Get<unknown | null>;
    getTreePageStep: (...args: unknown[]) => number;
    findTreeParentIndex: (...args: unknown[]) => number;
    getVisibleTreeNodes: (...args: unknown[]) => unknown[];
  }) => {
    expandTreeNode: (path: string, depth: number, autoExpand: boolean) => Promise<void>;
    buildTreeRoot: (path: string) => Promise<void>;
    selectTreeNode: (node: unknown, index: number) => void;
    toggleTreeNode: (node: unknown, index: number, event?: MouseEvent) => void;
    handleTreeKey: (event: KeyboardEvent) => unknown;
  };
  invoke: InvokeFn;
  getShowHidden: Get<boolean>;
  showError: (err: unknown) => void;
  createTreeNode: (...args: unknown[]) => unknown;
  isTreeListIgnorableError: (err: unknown) => boolean;
  autoExpandDepth: number;
  setTreeRoot: Set<unknown | null>;
  setTreeSelectedPath: Set<string>;
  setTreeFocusedIndex: Set<number>;
  getTreeBodyEl: Get<HTMLElement | null>;
  scrollTreeToFocus: (treeBodyEl: HTMLElement | null, focusedIndex: number) => void;
  getCurrentPath: Get<string>;
  getLoadDir: Get<(path: string) => Promise<void>>;
  setTreeLoading: Set<boolean>;
  handleTreeKeyUtil: (event: KeyboardEvent) => unknown;
  matchesAction: (event: KeyboardEvent, action: string) => boolean;
  getTreeFocusedIndex: Get<number>;
  getTreeEl: Get<HTMLElement | null>;
  getTreeRootSafe: Get<unknown | null>;
  getTreePageStep: (...args: unknown[]) => number;
  findTreeParentIndex: (...args: unknown[]) => number;
  getVisibleTreeNodes: (...args: unknown[]) => unknown[];
  setExpandTreeNode: Set<(path: string, depth: number, autoExpand: boolean) => Promise<void>>;
  setBuildTreeRoot: Set<(path: string) => Promise<void>>;
  setSelectTreeNode: Set<(node: unknown, index: number) => void>;
  setToggleTreeNode: Set<(node: unknown, index: number, event?: MouseEvent) => void>;
  setHandleTreeKey: Set<(event: KeyboardEvent) => unknown>;
  markReady: MarkReady;
};

export type DirSectionParams = {
  createDirHelpers: (args: {
    invoke: InvokeFn;
    getShowHidden: Get<boolean>;
    getSortKey: Get<string>;
    getSortOrder: Get<string>;
    setEntries: Set<unknown[]>;
    setCurrentPath: Set<string>;
    setPathInput: Set<string>;
    scheduleWatch: (path: string) => void;
    setSelectedPaths: Set<string[]>;
    setFocusedIndex: Set<number>;
    setAnchorIndex: Set<number | null>;
    getPathHistory: Get<string[]>;
    setPathHistory: Set<string[]>;
    scheduleUiSave: () => void;
    getShowTree: Get<boolean>;
    buildTreeRoot: (path: string) => Promise<void>;
    clearTree: () => void;
    setLoading: Set<boolean>;
    setError: Set<unknown>;
    showError: (err: unknown) => void;
  }) => { loadDir: (path: string) => Promise<void> };
  invoke: InvokeFn;
  getShowHidden: Get<boolean>;
  getSortKey: Get<string>;
  getSortOrder: Get<string>;
  setEntries: Set<unknown[]>;
  setCurrentPath: Set<string>;
  setPathInput: Set<string>;
  getScheduleWatch: Get<(path: string) => void>;
  setSelectedPaths: Set<string[]>;
  setFocusedIndex: Set<number>;
  setAnchorIndex: Set<number | null>;
  getPathHistory: Get<string[]>;
  setPathHistory: Set<string[]>;
  getScheduleUiSave: Get<() => void>;
  getShowTree: Get<boolean>;
  getBuildTreeRoot: Get<(path: string) => Promise<void>>;
  clearTree: () => void;
  setLoading: Set<boolean>;
  setError: Set<unknown>;
  showError: (err: unknown) => void;
  setLoadDir: Set<(path: string) => Promise<void>>;
  markReady: MarkReady;
};

export type UiFlagsSectionParams = {
  createUiFlagHelpers: (args: {
    getShowHidden: Get<boolean>;
    setShowHidden: Set<boolean>;
    getShowTree: Get<boolean>;
    setShowTree: Set<boolean>;
    getTheme: Get<"light" | "dark">;
    setTheme: Set<"light" | "dark">;
    getScheduleUiSave: Get<() => void>;
    getLoadDir: Get<(path: string) => Promise<void>>;
    getCurrentPath: Get<string>;
    getFocusList: Get<() => void>;
    getBuildTreeRoot: Get<(path: string) => Promise<void>>;
    getUpdateListRows: Get<() => void>;
    tick: () => Promise<void>;
    getShowError: Get<(err: unknown) => void>;
  }) => { toggleHidden: () => void; toggleTree: () => void; toggleTheme: () => void };
  getShowHidden: Get<boolean>;
  setShowHidden: Set<boolean>;
  getShowTree: Get<boolean>;
  setShowTree: Set<boolean>;
  getTheme: Get<"light" | "dark">;
  setTheme: Set<"light" | "dark">;
  getScheduleUiSave: Get<() => void>;
  getLoadDir: Get<(path: string) => Promise<void>>;
  getCurrentPath: Get<string>;
  getFocusList: Get<() => void>;
  getBuildTreeRoot: Get<(path: string) => Promise<void>>;
  getUpdateListRows: Get<() => void>;
  tick: () => Promise<void>;
  getShowError: Get<(err: unknown) => void>;
  setToggleHidden: Set<() => void>;
  setToggleTree: Set<() => void>;
  setToggleTheme: Set<() => void>;
  markReady: MarkReady;
};

export type SortMenuSectionParams = {
  createSortMenuHelpers: (args: {
    getSortMenuOpen: Get<boolean>;
    setSortMenuOpen: Set<boolean>;
    getSortMenuIndex: Get<number>;
    setSortMenuIndex: Set<number>;
    getSortKey: Get<string>;
    setSortKey: Set<string>;
    getSortOrder: Get<string>;
    setSortOrder: Set<string>;
    getSortMenuEl: Get<HTMLElement | null>;
    trapModalTab: (event: KeyboardEvent) => void;
    scheduleUiSave: () => void;
    loadCurrentDir: () => void;
    tick: () => Promise<void>;
  }) => {
    setSort: (nextKey: string) => void;
    openSortMenu: () => void;
    closeSortMenu: () => void;
    handleSortMenuKey: (event: KeyboardEvent) => void;
  };
  getSortMenuOpen: Get<boolean>;
  setSortMenuOpen: Set<boolean>;
  getSortMenuIndex: Get<number>;
  setSortMenuIndex: Set<number>;
  getSortKey: Get<string>;
  setSortKey: Set<string>;
  getSortOrder: Get<string>;
  setSortOrder: Set<string>;
  getSortMenuEl: Get<HTMLElement | null>;
  trapModalTab: (event: KeyboardEvent) => void;
  getScheduleUiSave: Get<() => void>;
  loadCurrentDir: () => void;
  tick: () => Promise<void>;
  setSetSort: Set<(nextKey: string) => void>;
  setOpenSortMenu: Set<() => void>;
  setCloseSortMenu: Set<() => void>;
  setHandleSortMenuKey: Set<(event: KeyboardEvent) => void>;
  markReady: MarkReady;
};

export type SearchSectionParams = {
  createSearchHelpers: (args: {
    computeSearchEffect: (...args: unknown[]) => { filteredEntries: unknown[]; error?: string };
    applySearchFilter: (...args: unknown[]) => unknown[];
    getEntries: Get<unknown[]>;
    getSearchActive: Get<boolean>;
    getSearchQuery: Get<string>;
    getSearchRegex: Get<boolean>;
    setFilteredEntries: Set<unknown[]>;
    setSearchError: Set<string>;
    t: (key: string, vars?: Record<string, string | number>) => string;
  }) => { recomputeSearch: () => void };
  computeSearchEffect: (...args: unknown[]) => { filteredEntries: unknown[]; error?: string };
  applySearchFilter: (...args: unknown[]) => unknown[];
  getEntries: Get<unknown[]>;
  getSearchActive: Get<boolean>;
  getSearchQuery: Get<string>;
  getSearchRegex: Get<boolean>;
  setFilteredEntries: Set<unknown[]>;
  setSearchError: Set<string>;
  t: (key: string, vars?: Record<string, string | number>) => string;
  setRecomputeSearch: Set<() => void>;
  markReady: MarkReady;
};

export type DerivedSectionParams = {
  createDerivedEffects: (args: {
    computeDropdownItems: (...args: unknown[]) => unknown[];
    buildDropdownItems: (...args: unknown[]) => unknown[];
    getDropdownMode: Get<"history" | "jump">;
    getJumpList: Get<unknown[]>;
    getPathHistory: Get<string[]>;
    setDropdownItems: Set<unknown[]>;
    buildStatusItems: (...args: unknown[]) => string[];
    getStatusMessage: Get<string>;
    getSortKey: Get<string>;
    getSortOrder: Get<string>;
    getSelectedCount: Get<number>;
    getShowHidden: Get<boolean>;
    getSearchActive: Get<boolean>;
    getSearchQuery: Get<string>;
    setStatusItems: Set<string[]>;
    clampDropdownIndex: (...args: unknown[]) => number;
    getDropdownOpen: Get<boolean>;
    getDropdownIndex: Get<number>;
    setDropdownIndex: Set<number>;
    getDropdownItems: Get<unknown[]>;
    t: (key: string, vars?: Record<string, string | number>) => string;
  }) => {
    recomputeDropdownItems: () => void;
    recomputeStatusItems: () => void;
    clampDropdownSelection: () => void;
  };
  computeDropdownItems: (...args: unknown[]) => unknown[];
  buildDropdownItems: (...args: unknown[]) => unknown[];
  getDropdownMode: Get<"history" | "jump">;
  getJumpList: Get<unknown[]>;
  getPathHistory: Get<string[]>;
  setDropdownItems: Set<unknown[]>;
  buildStatusItems: (...args: unknown[]) => string[];
  getStatusMessage: Get<string>;
  getSortKey: Get<string>;
  getSortOrder: Get<string>;
  getSelectedCount: Get<number>;
  getShowHidden: Get<boolean>;
  getSearchActive: Get<boolean>;
  getSearchQuery: Get<string>;
  setStatusItems: Set<string[]>;
  clampDropdownIndex: (...args: unknown[]) => number;
  getDropdownOpen: Get<boolean>;
  getDropdownIndex: Get<number>;
  setDropdownIndex: Set<number>;
  getDropdownItems: Get<unknown[]>;
  t: (key: string, vars?: Record<string, string | number>) => string;
  setRecomputeDropdownItems: Set<() => void>;
  setRecomputeStatusItems: Set<() => void>;
  setClampDropdownSelection: Set<() => void>;
  markReady: MarkReady;
};
