import type { DomHandlersInputsFromVars } from "$lib/page_dom_handlers_inputs_from_vars_types";

export function buildDomHandlersSetupInputsFromVars(params: DomHandlersInputsFromVars) {
  const getState = typeof params.state === "function" ? params.state : () => params.state;
  const getActions = typeof params.actions === "function" ? params.actions : () => params.actions;
  const getHelpers = typeof params.helpers === "function" ? params.helpers : () => params.helpers;
  const action = (key) => (...args) => getActions()[key](...args);
  const readState = (key) => () => getState()[key];

  return {
    state: {
      getListEl: readState("listEl"),
      getPathInputEl: readState("pathInputEl"),
      getTreeEl: readState("treeEl"),
      getDropdownEl: readState("dropdownEl"),
      getContextMenuEl: readState("contextMenuEl"),
      getPasteConfirmOpen: readState("pasteConfirmOpen"),
      getDeleteConfirmOpen: readState("deleteConfirmOpen"),
      getJumpUrlOpen: readState("jumpUrlOpen"),
      getSortMenuOpen: readState("sortMenuOpen"),
      getZipModalOpen: readState("zipModalOpen"),
      getFailureModalOpen: readState("failureModalOpen"),
      getDropdownOpen: readState("dropdownOpen"),
      getRenameOpen: readState("renameOpen"),
      getCreateOpen: readState("createOpen"),
      getPropertiesOpen: readState("propertiesOpen"),
      getContextMenuOpen: readState("contextMenuOpen"),
      getShowTree: readState("showTree"),
      getShowHidden: readState("showHidden"),
      getShowSize: readState("showSize"),
      getShowTime: readState("showTime"),
      getSearchActive: readState("searchActive"),
      getCurrentPath: readState("currentPath"),
      getDropdownMode: readState("dropdownMode"),
      getEntries: readState("entries"),
      getFocusedIndex: readState("focusedIndex"),
      getListRows: readState("listRows"),
      getSelectedPaths: readState("selectedPaths"),
      getJumpList: readState("jumpList"),
      getPathHistory: readState("pathHistory"),
      getMenuOpen: readState("menuOpen"),
      getMenuBarEl: readState("menuBarEl"),
    },
    actions: {
      matchesAction: action("matchesAction"),
      handleSortMenuKey: action("handleSortMenuKey"),
      focusTreeTop: action("focusTreeTop"),
      focusList: action("focusList"),
      cancelRename: action("cancelRename"),
      confirmRename: action("confirmRename"),
      cancelCreate: action("cancelCreate"),
      confirmCreate: action("confirmCreate"),
      cancelJumpUrl: action("cancelJumpUrl"),
      confirmJumpUrl: action("confirmJumpUrl"),
      closeProperties: action("closeProperties"),
      handleContextMenuKey: action("handleContextMenuKey"),
      openConfigFile: action("openConfigFile"),
      openKeymapHelp: action("openKeymapHelp"),
      handleTreeKey: action("handleTreeKey"),
      performUndo: action("performUndo"),
      performRedo: action("performRedo"),
      clearDirStatsCache: action("clearDirStatsCache"),
      setStatusMessage: action("setStatusMessage"),
      selectAll: action("selectAll"),
      setSelected: action("setSelected"),
      setAnchorIndex: action("setAnchorIndex"),
      updateListRows: action("updateListRows"),
      scheduleUiSave: action("scheduleUiSave"),
      buildTreeRoot: action("buildTreeRoot"),
      showError: action("showError"),
      openInExplorer: action("openInExplorer"),
      openInCmd: action("openInCmd"),
      openInVSCode: action("openInVSCode"),
      openInGitClient: action("openInGitClient"),
      openZipCreate: action("openZipCreate"),
      openZipExtract: action("openZipExtract"),
      openProperties: action("openProperties"),
      loadDir: action("loadDir"),
      moveFocusByRow: action("moveFocusByRow"),
      moveFocusByColumn: action("moveFocusByColumn"),
      toggleSelection: action("toggleSelection"),
      selectRange: action("selectRange"),
      openEntry: action("openEntry"),
      openRename: action("openRename"),
      openCreate: action("openCreate"),
      copySelected: action("copySelected"),
      duplicateSelected: action("duplicateSelected"),
      prefixDateSelected: action("prefixDateSelected"),
      cutSelected: action("cutSelected"),
      pasteItems: action("pasteItems"),
      addJumpCurrent: action("addJumpCurrent"),
      openJumpUrlModal: action("openJumpUrlModal"),
      openSortMenu: action("openSortMenu"),
      closeSortMenu: action("closeSortMenu"),
      getExternalApps: action("getExternalApps"),
      runExternalApp: action("runExternalApp"),
      setDropdownMode: action("setDropdownMode"),
      setDropdownOpen: action("setDropdownOpen"),
      setSearchActive: action("setSearchActive"),
      setPathInput: action("setPathInput"),
      setShowHidden: action("setShowHidden"),
      setShowSize: action("setShowSize"),
      setShowTime: action("setShowTime"),
      setShowTree: action("setShowTree"),
      setDeleteTargets: action("setDeleteTargets"),
      setDeleteConfirmOpen: action("setDeleteConfirmOpen"),
      setDeleteConfirmIndex: action("setDeleteConfirmIndex"),
      setDeleteError: action("setDeleteError"),
      setPathHistory: action("setPathHistory"),
      exitApp: action("exitApp"),
      focusPathInput: action("focusPathInput"),
      getTargetEntry: action("getTargetEntry"),
      closeContextMenu: action("closeContextMenu"),
      closeMenu: action("closeMenu"),
    },
    helpers: {
      handleGlobalKey: (...args) => getHelpers().handleGlobalKey(...args),
      t: (...args) => getHelpers().t(...args),
      confirm: (...args) => getHelpers().confirm(...args),
      eventToKeyString: (...args) => getHelpers().eventToKeyString(...args),
      normalizeKeyString: (...args) => getHelpers().normalizeKeyString(...args),
    },
    constants: params.constants,
  };
}

