/**
 * @param {object} params
 */
export function buildLifecycleParams(params) {
  return {
    homeDir: params.homeDir,
    invoke: params.invoke,
    listen: params.listen,
    EVENT_FS_CHANGED: params.EVENT_FS_CHANGED,
    EVENT_OP_PROGRESS: params.EVENT_OP_PROGRESS,
    setStatusMessage: params.setStatusMessage,
    showError: params.showError,
    loadDir: params.loadDir,
    getCurrentPath: params.getCurrentPath,
    getWatchRefreshTimer: params.getWatchRefreshTimer,
    setWatchRefreshTimer: params.setWatchRefreshTimer,
    setDirStatsTimeoutMs: params.setDirStatsTimeoutMs,
    setShowHidden: params.setShowHidden,
    setShowSize: params.setShowSize,
    setShowTime: params.setShowTime,
    setShowTree: params.setShowTree,
    setSortKey: params.setSortKey,
    setSortOrder: params.setSortOrder,
    setUiTheme: params.setUiTheme,
    setUiLanguage: params.setUiLanguage,
    setUiFileIconMode: params.setUiFileIconMode,
    setKeymapProfile: params.setKeymapProfile,
    setExternalAppAssociations: params.setExternalAppAssociations,
    setExternalApps: params.setExternalApps,
    setKeymapCustom: params.setKeymapCustom,
    setLoggingEnabled: params.setLoggingEnabled,
    setLogFile: params.setLogFile,
    setPathHistory: params.setPathHistory,
    setJumpList: params.setJumpList,
    setSearchHistory: params.setSearchHistory,
    updateWindowBounds: params.updateWindowBounds,
    setUiConfigLoaded: params.setUiConfigLoaded,
    getCurrentWindow: params.getCurrentWindow,
    setWindowBounds: params.setWindowBounds,
    setWindowBoundsReady: params.setWindowBoundsReady,
    scheduleUiSave: params.scheduleUiSave,
    onBeforeUnload: params.onBeforeUnload,
    onKeyDown: params.onKeyDown,
    onClick: params.onClick,
    recomputeStatusItems: params.recomputeStatusItems,
    setUpdateWindowBounds: params.setUpdateWindowBounds,
    t: params.t,
  };
}
