/**
 * @param {object} groups
 */
export function buildPageSettersInputsFromGroups(groups) {
  return {
    setPasteConfirmOpen: groups.paste.setPasteConfirmOpen,
    setPastePendingPaths: groups.paste.setPastePendingPaths,
    setPasteConflicts: groups.paste.setPasteConflicts,
    setPasteConfirmIndex: groups.paste.setPasteConfirmIndex,
    setPasteMode: groups.paste.setPasteMode,
    setPasteApplyAll: groups.paste.setPasteApplyAll,
    setDeleteConfirmOpen: groups.delete.setDeleteConfirmOpen,
    setDeleteTargets: groups.delete.setDeleteTargets,
    setDeleteError: groups.delete.setDeleteError,
    setDeleteConfirmIndex: groups.delete.setDeleteConfirmIndex,
    setRenameTarget: groups.rename.setRenameTarget,
    setRenameValue: groups.rename.setRenameValue,
    setRenameError: groups.rename.setRenameError,
    setRenameOpen: groups.rename.setRenameOpen,
    setCreateType: groups.create.setCreateType,
    setCreateName: groups.create.setCreateName,
    setCreateError: groups.create.setCreateError,
    setCreateOpen: groups.create.setCreateOpen,
    setJumpUrlOpen: groups.jump.setJumpUrlOpen,
    setJumpUrlError: groups.jump.setJumpUrlError,
    setJumpUrlValue: groups.jump.setJumpUrlValue,
    setJumpList: groups.jump.setJumpList,
    setPathHistory: groups.jump.setPathHistory,
    setSearchQuery: groups.search.setSearchQuery,
    setSearchActive: groups.search.setSearchActive,
    setSearchError: groups.search.setSearchError,
    setSearchHistory: groups.search.setSearchHistory,
    setAboutOpen: groups.about.setAboutOpen,
    setFocusedIndex: groups.selection.setFocusedIndex,
    setSelected: groups.selection.setSelected,
    setAnchorIndex: groups.selection.setAnchorIndex,
    setContextMenuOpen: groups.contextMenu.setContextMenuOpen,
    setContextMenuPos: groups.contextMenu.setContextMenuPos,
    setContextMenuMode: groups.contextMenu.setContextMenuMode,
    setContextMenuCanPaste: groups.contextMenu.setContextMenuCanPaste,
    setContextMenuIndex: groups.contextMenu.setContextMenuIndex,
    setDropdownOpen: groups.dropdown.setDropdownOpen,
    setStatusMessageState: groups.status.setStatusMessageState,
    setStatusTimer: groups.status.setStatusTimer,
    setError: groups.failure.setError,
    setFailureModalOpen: groups.failure.setFailureModalOpen,
    setFailureModalTitle: groups.failure.setFailureModalTitle,
    setFailureItems: groups.failure.setFailureItems,
    setLastClipboard: groups.clipboard.setLastClipboard,
    setUndoStack: groups.undo.setUndoStack,
    setRedoStack: groups.undo.setRedoStack,
    setZipMode: groups.zip.setZipMode,
    setZipTargets: groups.zip.setZipTargets,
    setZipDestination: groups.zip.setZipDestination,
    setZipPassword: groups.zip.setZipPassword,
    setZipError: groups.zip.setZipError,
    setZipPasswordAttempts: groups.zip.setZipPasswordAttempts,
    setZipConfirmIndex: groups.zip.setZipConfirmIndex,
    setZipOverwriteConfirmed: groups.zip.setZipOverwriteConfirmed,
    setZipModalOpen: groups.zip.setZipModalOpen,
  };
}
