/**
 * @param {object} params
 * @param {(actionId: import("$lib/ui_types").ActionId) => string} params.getMenuShortcut
 */
export function buildMenuItemsParams(params) {
  return {
    t: params.t,
    getMenuShortcut: params.getMenuShortcut,
    openFocusedOrSelected: params.openFocusedOrSelected,
    openParentForSelection: params.openParentForSelection,
    openInExplorer: params.openInExplorer,
    openInCmd: params.openInCmd,
    openInVSCode: params.openInVSCode,
    openInGitClient: params.openInGitClient,
    copySelected: params.copySelected,
    duplicateSelected: params.duplicateSelected,
    prefixDateSelected: params.prefixDateSelected,
    cutSelected: params.cutSelected,
    pasteItems: params.pasteItems,
    hasOperationTargets: params.hasOperationTargets,
    hasSelection: params.hasSelection,
    canPasteCurrentPath: params.canPasteCurrentPath,
    canCopyTargets: params.canCopyTargets,
    canDuplicateTargets: params.canDuplicateTargets,
    canPrefixDateTargets: params.canPrefixDateTargets,
    canCutTargets: params.canCutTargets,
    canDeleteSelection: params.canDeleteSelection,
    canOpenPropertiesSelection: params.canOpenPropertiesSelection,
    requestDeleteSelected: params.requestDeleteSelected,
    requestOpenPropertiesSelected: params.requestOpenPropertiesSelected,
    invokeExit: params.invokeExit,
    performUndo: params.performUndo,
    performRedo: params.performRedo,
    openConfigFile: params.openConfigFile,
    selectAll: params.selectAll,
    clearSelection: params.clearSelection,
    invertSelection: params.invertSelection,
    openSearch: params.openSearch,
    openSortMenu: params.openSortMenu,
    toggleHidden: params.toggleHidden,
    toggleTree: params.toggleTree,
    toggleTheme: params.toggleTheme,
    refresh: params.refresh,
    addJumpCurrent: params.addJumpCurrent,
    openJumpUrlModal: params.openJumpUrlModal,
    openJumpList: params.openJumpList,
    openHistoryList: params.openHistoryList,
    openKeymapHelp: params.openKeymapHelp,
    openUserManual: params.openUserManual,
    openAbout: params.openAbout,
    closeMenu: params.closeMenu,
    getShowHidden: params.getShowHidden,
    getShowTree: params.getShowTree,
    getTheme: params.getTheme,
    hasJumpList: params.hasJumpList,
    hasPathHistory: params.hasPathHistory,
    setStatusMessage: params.setStatusMessage,
  };
}
