/**
 * @param {{
 *   setStatusMessage?: (value: string) => void;
 *   showError?: (err: unknown) => void;
 * }} params
 */
export function createPageActionPlaceholders(
  params: {
    setStatusMessage?: (value: string) => void;
    showError?: (err: unknown) => void;
  } = {}
) {
  const noop = () => {};
  const noopAsync = async () => {};

  return {
    saveUiStateNow: noopAsync,
    scheduleUiSave: noop,
    openProperties: noopAsync,
    closeProperties: noop,
    startDirStats: noopAsync,
    cancelDirStats: noop,
    retryDirStats: noop,
    saveDirStatsTimeout: noopAsync,
    loadDir: noopAsync,
    scheduleWatch: noop,
    focusList: noop,
    focusTree: noop,
    focusTreeTop: noop,
    updateListRows: noop,
    updateOverflowMarkers: noop,
    updateVisibleColumns: noop,
    setScrollStartColumn: noop,
    ensureColumnVisible: noop,
    scrollListHorizontallyByColumns: noop,
    getActualColumnSpan: () => 1,
    expandTreeNode: noopAsync,
    buildTreeRoot: noopAsync,
    selectTreeNode: noop,
    toggleTreeNode: noop,
    handleTreeKey: noop,
    setSort: noop,
    openSortMenu: noop,
    closeSortMenu: noop,
    handleSortMenuKey: noop,
    toggleHidden: noop,
    toggleTree: noop,
    toggleTheme: noop,
    recomputeSearch: noop,
    recomputeDropdownItems: noop,
    recomputeStatusItems: noop,
    clampDropdownSelection: noop,
    setStatusMessage: params.setStatusMessage ?? noop,
    cancelRename: noop,
    confirmRename: noop,
    cancelCreate: noop,
    confirmCreate: noop,
    confirmPasteOverwrite: noop,
    confirmPasteSkip: noop,
    confirmPasteKeepBoth: noop,
    cancelPasteConfirm: noop,
    confirmDelete: noop,
    cancelDelete: noop,
    runZipAction: noop,
    closeZipModal: noop,
    showFailures: noop,
    failureMessage: () => "",
    closeFailureModal: noop,
    applySearch: noop,
    clearSearch: noop,
    onSearchKeydown: noop,
    scrollDropdownToIndex: noop,
    removeJump: noop,
    removeHistory: noop,
    selectDropdown: noop,
    showErrorAction: params.showError ?? noop,
    cancelJumpUrl: noop,
    confirmJumpUrl: noop,
    handleContextMenuKey: noop,
    openConfigFile: noopAsync,
    openKeymapHelp: noopAsync,
    refreshGdriveWorkcopyBadges: noopAsync,
    performUndo: noop,
    performRedo: noop,
    selectAll: noop,
    setSelected: noop,
    toggleSelection: noop,
    selectRange: noop,
    openEntry: noopAsync,
    openRename: noop,
    openCreate: noop,
    openFocusedOrSelected: noop,
    openParentForSelection: noop,
    openUserManual: noop,
    openAbout: noop,
    closeAbout: noop,
    copySelected: noop,
    duplicateSelected: noop,
    prefixDateSelected: noop,
    cutSelected: noop,
    pasteItems: noop,
    hasOperationTargets: () => false,
    hasSelection: () => false,
    canCreateCurrentPath: () => false,
    canPasteCurrentPath: () => false,
    canCopyTargets: () => false,
    canDuplicateTargets: () => false,
    canPrefixDateTargets: () => false,
    canCutTargets: () => false,
    canRenameFocused: () => false,
    canDeleteSelection: () => false,
    canDeleteTargets: () => false,
    canOpenPropertiesSelection: () => false,
    canZipCreateSelection: () => false,
    canZipExtractSelection: () => false,
    canZipExtractFocused: () => false,
    addJumpCurrent: noop,
    openJumpUrlModal: noop,
    openInExplorer: noop,
    openInCmd: noop,
    openInTerminalCmd: noop,
    openInTerminalPowerShell: noop,
    openInTerminalWsl: noop,
    openInVSCode: noop,
    openInGitClient: noop,
    openZipCreate: noop,
    openZipExtract: noop,
    openContextMenu: noop,
    closeContextMenu: noop,
    getSelectableIndex: () => 0,
    getContextMenuItems: () => [],
    requestDeleteSelected: noop,
    requestOpenPropertiesSelected: noop,
    getExternalApps: () => [],
    runExternalApp: noop,
    getTargetEntry: () => null,
    toggleMenu: noop,
    closeMenu: noop,
    getMenuItems: () => [],
    pushUndoEntry: noop,
    clearSelection: noop,
    invertSelection: noop,
    openJumpList: noop,
    openHistoryList: noop,
    handlePathTabCompletion: noopAsync,
    matchesAction: () => false,
    moveFocusByRow: noop,
    moveFocusByColumn: noop,
  };
}
