
/**
 * @param {{
 *   state: {
 *     menuOpen: boolean;
 *     currentPath: string;
 *     pathHistory: string[];
 *     showTree: boolean;
 *     treeEl: HTMLElement | null;
 *     treeLoading: boolean;
 *     treeRoot: any;
 *     treeSelectedPath: string;
 *     treeFocusedIndex: number;
 *     showSize: boolean;
 *     showTime: boolean;
 *     loading: boolean;
 *     filteredEntries: any[];
 *     entries: any[];
 *     overflowLeft: boolean;
 *     overflowRight: boolean;
 *     visibleColStart: number;
 *     visibleColEnd: number;
 *     listRows: number;
 *     selectedPaths: string[];
 *     dropdownItems: any[];
 *     searchActive: boolean;
 *     searchError: string;
 *     sortMenuOpen: boolean;
 *     aboutOpen: boolean;
 *     deleteConfirmOpen: boolean;
 *     deleteTargets: string[];
 *     deleteError: string;
 *     pasteConfirmOpen: boolean;
 *     pasteConflicts: any[];
 *     createOpen: boolean;
 *     createError: string;
 *     jumpUrlOpen: boolean;
 *     renameOpen: boolean;
 *     renameError: string;
 *     propertiesOpen: boolean;
 *     propertiesData: any;
 *     dirStatsInFlight: boolean;
 *     zipModalOpen: boolean;
 *     zipMode: string;
 *     zipTargets: string[];
 *     zipPasswordAttempts: number;
 *     zipOverwriteConfirmed: boolean;
 *     zipError: string;
 *     contextMenuOpen: boolean;
 *     contextMenuPos: { x: number; y: number } | null;
 *     contextMenuIndex: number;
 *     error: string;
 *     failureModalOpen: boolean;
 *     failureModalTitle: string;
 *     failureItems: any[];
 *     jumpList: string[];
 *   };
 *   actions: {
 *     pageActions: any;
 *     toggleMenu: () => void;
 *     getMenuItems: () => any[];
 *     closeMenu: () => void;
 *     loadDir: (path: string) => Promise<void>;
 *     focusList: () => void;
 *     focusTreeTop: () => void;
 *     handlePathTabCompletion: (event: KeyboardEvent) => void;
 *     setStatusMessage: (message: string, timeoutMs?: number) => void;
 *     getVisibleTreeNodes: () => any[];
 *     focusTree: () => void;
 *     selectTreeNode: (node: any) => void;
 *     toggleTreeNode: (node: any) => void;
 *     matchesAction: (action: string, binding: string) => boolean;
 *     trapModalTab: (event: KeyboardEvent) => void;
 *     setSort: (key: string, order?: string) => void;
 *     handleSortMenuKey: (event: KeyboardEvent) => void;
 *     openUrl: (url: string) => Promise<void>;
 *     saveDirStatsTimeout: (value: number) => void;
 *     clearDirStatsCache: () => void;
 *     retryDirStats: () => void;
 *     cancelDirStats: () => void;
 *     closeProperties: () => void;
 *     autofocus: (el: HTMLElement | null) => void;
 *     getContextMenuItems: () => any[];
 *     getSelectableIndex: (index: number) => number | null;
 *     handleContextMenuKey: (event: KeyboardEvent) => void;
 *     failureMessage: string;
 *   };
 *   meta: {
 *     formatName: (value: string, maxChars?: number) => string;
 *     formatSize: (value: number) => string;
 *     formatModified: (value: number | Date) => string;
 *     MENU_GROUPS: any;
 *     ABOUT_URL: string;
 *     ABOUT_LICENSE: string;
 *     ZIP_PASSWORD_MAX_ATTEMPTS: number;
 *     t: (value: string) => string;
 *   };
 *   overlay: {
 *     dropdownEl: HTMLElement | null;
 *     dropdownMode: string;
 *     dropdownOpen: boolean;
 *     dropdownIndex: number;
 *     searchQuery: string;
 *     searchRegex: boolean;
 *     searchInputEl: HTMLInputElement | null;
 *     sortMenuIndex: number;
 *     sortMenuEl: HTMLElement | null;
 *     aboutModalEl: HTMLElement | null;
 *     deleteModalEl: HTMLElement | null;
 *     deleteConfirmIndex: number;
 *     pasteModalEl: HTMLElement | null;
 *     pasteApplyAll: boolean;
 *     pasteConfirmIndex: number;
 *     createModalEl: HTMLElement | null;
 *     createInputEl: HTMLInputElement | null;
 *     createType: "file" | "folder";
 *     createName: string;
 *     jumpUrlModalEl: HTMLElement | null;
 *     jumpUrlInputEl: HTMLInputElement | null;
 *     jumpUrlValue: string;
 *     jumpUrlError: string;
 *     renameModalEl: HTMLElement | null;
 *     renameInputEl: HTMLInputElement | null;
 *     renameValue: string;
 *     propertiesModalEl: HTMLElement | null;
 *     propertiesCloseButton: HTMLButtonElement | null;
 *     dirStatsTimeoutMs: number;
 *     zipModalEl: HTMLElement | null;
 *     zipDestination: string;
 *     zipPassword: string;
 *     zipConfirmIndex: number;
 *     zipOverwriteConfirmed: boolean;
 *     contextMenuEl: HTMLElement | null;
 *     failureModalEl: HTMLElement | null;
 *   };
 * }} params
 */

export type ViewInputsParams = Record<string, unknown>;
