/**
 * @param {object} params
 */
export function buildViewPropsInputsState(params) {
  const { state } = params;

  return {
    menuOpen: state.menu.menuOpen,
    currentPath: state.path.currentPath,
    pathHistory: state.path.pathHistory,
    showTree: state.tree.showTree,
    treeEl: state.tree.treeEl,
    treeLoading: state.tree.treeLoading,
    treeRoot: state.tree.treeRoot,
    treeSelectedPath: state.tree.treeSelectedPath,
    treeFocusedIndex: state.tree.treeFocusedIndex,
    showSize: state.list.showSize,
    showTime: state.list.showTime,
    uiFileIconMode: state.list.uiFileIconMode,
    loading: state.list.loading,
    filteredEntries: state.list.filteredEntries,
    pathCompletionPreviewActive: state.list.pathCompletionPreviewActive,
    entries: state.list.entries,
    overflowLeft: state.list.overflowLeft,
    overflowRight: state.list.overflowRight,
    visibleColStart: state.list.visibleColStart,
    visibleColEnd: state.list.visibleColEnd,
    listRows: state.list.listRows,
    selectedPaths: state.list.selectedPaths,
    dropdownItems: state.dropdown.dropdownItems,
    searchActive: state.dropdown.searchActive,
    searchError: state.dropdown.searchError,
    sortMenuOpen: state.dropdown.sortMenuOpen,
    aboutOpen: state.modals.aboutOpen,
    deleteConfirmOpen: state.modals.deleteConfirmOpen,
    deleteTargets: state.modals.deleteTargets,
    deleteError: state.modals.deleteError,
    pasteConfirmOpen: state.modals.pasteConfirmOpen,
    pasteConflicts: state.modals.pasteConflicts,
    createOpen: state.modals.createOpen,
    createError: state.modals.createError,
    jumpUrlOpen: state.modals.jumpUrlOpen,
    renameOpen: state.modals.renameOpen,
    renameError: state.modals.renameError,
    propertiesOpen: state.modals.propertiesOpen,
    propertiesData: state.modals.propertiesData,
    dirStatsInFlight: state.modals.dirStatsInFlight,
    zipModalOpen: state.modals.zipModalOpen,
    zipMode: state.modals.zipMode,
    zipTargets: state.modals.zipTargets,
    zipPasswordAttempts: state.modals.zipPasswordAttempts,
    zipOverwriteConfirmed: state.modals.zipOverwriteConfirmed,
    zipError: state.modals.zipError,
    contextMenuOpen: state.context.contextMenuOpen,
    contextMenuPos: state.context.contextMenuPos,
    contextMenuIndex: state.context.contextMenuIndex,
    error: state.context.error,
    failureModalOpen: state.context.failureModalOpen,
    failureModalTitle: state.context.failureModalTitle,
    failureItems: state.context.failureItems,
    jumpList: state.context.jumpList,
  };
}
