export function buildMenuProps(params) {
  return {
    MENU_GROUPS: params.MENU_GROUPS,
    menuOpen: params.menuOpen,
    t: params.t,
    toggleMenu: params.toggleMenu,
    getMenuItems: params.getMenuItems,
    closeMenu: params.closeMenu,
  };
}

export function buildPathBarProps(params) {
  return {
    t: params.t,
    currentPath: params.currentPath,
    pathHistory: params.pathHistory,
    showTree: params.showTree,
    treeEl: params.treeEl,
    loadDir: params.loadDir,
    focusList: params.focusList,
    focusTreeTop: params.focusTreeTop,
    handlePathTabCompletion: params.handlePathTabCompletion,
    setStatusMessage: params.setStatusMessage,
  };
}

export function buildTreeProps(params) {
  return {
    treeLoading: params.treeLoading,
    treeRoot: params.treeRoot,
    treeSelectedPath: params.treeSelectedPath,
    treeFocusedIndex: params.treeFocusedIndex,
    t: params.t,
    getVisibleTreeNodes: params.getVisibleTreeNodes,
    focusTree: params.focusTree,
    selectTreeNode: params.selectTreeNode,
    toggleTreeNode: params.toggleTreeNode,
  };
}

export function buildFileListProps(params) {
  return {
    currentPath: params.currentPath,
    showSize: params.showSize,
    showTime: params.showTime,
    uiFileIconMode: params.uiFileIconMode,
    loading: params.loading,
    filteredEntries: params.filteredEntries,
    entries: params.entries,
    overflowLeft: params.overflowLeft,
    overflowRight: params.overflowRight,
    visibleColStart: params.visibleColStart,
    visibleColEnd: params.visibleColEnd,
    listRows: params.listRows,
    t: params.t,
    selectedPaths: params.selectedPaths,
    openContextMenu: params.openContextMenu,
    selectRange: params.selectRange,
    toggleSelection: params.toggleSelection,
    setSelected: params.setSelected,
    openEntry: params.openEntry,
    resolveGdriveWorkcopyBadge: params.resolveGdriveWorkcopyBadge,
    formatName: params.formatName,
    formatSize: params.formatSize,
    formatModified: params.formatModified,
  };
}

export function buildOverlayProps(params) {
  return {
    dropdownItems: params.dropdownItems,
    matchesAction: params.matchesAction,
    setStatusMessage: params.setStatusMessage,
    jumpList: params.jumpList,
    pathHistory: params.pathHistory,
    scrollDropdownToIndex: params.scrollDropdownToIndex,
    selectDropdown: params.selectDropdown,
    removeHistory: params.removeHistory,
    removeJump: params.removeJump,
    trapModalTab: params.trapModalTab,
    searchActive: params.searchActive,
    searchError: params.searchError,
    onSearchKeydown: params.onSearchKeydown,
    applySearch: params.applySearch,
    clearSearch: params.clearSearch,
    sortMenuOpen: params.sortMenuOpen,
    setSort: params.setSort,
    handleSortMenuKey: params.handleSortMenuKey,
    aboutOpen: params.aboutOpen,
    openUrl: params.openUrl,
    ABOUT_URL: params.ABOUT_URL,
    ABOUT_LICENSE: params.ABOUT_LICENSE,
    closeAbout: params.closeAbout,
    deleteConfirmOpen: params.deleteConfirmOpen,
    deleteTargets: params.deleteTargets,
    deleteError: params.deleteError,
    confirmDelete: params.confirmDelete,
    cancelDelete: params.cancelDelete,
    pasteConfirmOpen: params.pasteConfirmOpen,
    pasteConflicts: params.pasteConflicts,
    allowPasteKeepBoth: params.allowPasteKeepBoth,
    confirmPasteOverwrite: params.confirmPasteOverwrite,
    confirmPasteSkip: params.confirmPasteSkip,
    confirmPasteKeepBoth: params.confirmPasteKeepBoth,
    cancelPasteConfirm: params.cancelPasteConfirm,
    createOpen: params.createOpen,
    createError: params.createError,
    confirmCreate: params.confirmCreate,
    cancelCreate: params.cancelCreate,
    jumpUrlOpen: params.jumpUrlOpen,
    confirmJumpUrl: params.confirmJumpUrl,
    cancelJumpUrl: params.cancelJumpUrl,
    renameOpen: params.renameOpen,
    renameError: params.renameError,
    confirmRename: params.confirmRename,
    cancelRename: params.cancelRename,
    propertiesOpen: params.propertiesOpen,
    propertiesData: params.propertiesData,
    dirStatsInFlight: params.dirStatsInFlight,
    formatSize: params.formatSize,
    formatModified: params.formatModified,
    saveDirStatsTimeout: params.saveDirStatsTimeout,
    clearDirStatsCache: params.clearDirStatsCache,
    retryDirStats: params.retryDirStats,
    cancelDirStats: params.cancelDirStats,
    closeProperties: params.closeProperties,
    autofocus: params.autofocus,
    zipModalOpen: params.zipModalOpen,
    zipMode: params.zipMode,
    zipTargets: params.zipTargets,
    zipPasswordAttempts: params.zipPasswordAttempts,
    ZIP_PASSWORD_MAX_ATTEMPTS: params.ZIP_PASSWORD_MAX_ATTEMPTS,
    zipError: params.zipError,
    zipOverwriteConfirmed: params.zipOverwriteConfirmed,
    runZipAction: params.runZipAction,
    closeZipModal: params.closeZipModal,
    contextMenuOpen: params.contextMenuOpen,
    contextMenuPos: params.contextMenuPos,
    getContextMenuItems: params.getContextMenuItems,
    contextMenuIndex: params.contextMenuIndex,
    getSelectableIndex: params.getSelectableIndex,
    handleContextMenuKey: params.handleContextMenuKey,
    error: params.error,
    failureModalOpen: params.failureModalOpen,
    failureModalTitle: params.failureModalTitle,
    failureItems: params.failureItems,
    failureMessage: params.failureMessage,
    closeFailureModal: params.closeFailureModal,
    t: params.t,
  };
}
