import type { PageActionsPageParams } from "$lib/page_actions_page_types";

export function buildPageActionsPage(params: PageActionsPageParams) {
  const { state, set, refs, deps } = params;
  const {
    paste,
    delete: deleteSet,
    rename,
    create,
    jump,
    search,
    about,
    selection,
    contextMenu,
    dropdown,
    status,
    failure,
    clipboard,
    undo,
    zip,
  } = set;
  const resolve = (value) => (typeof value === "function" ? value() : value);
  return {
    getPastePendingPaths: () => resolve(state.pastePendingPaths),
    getPasteConflicts: () => resolve(state.pasteConflicts),
    getPasteMode: () => resolve(state.pasteMode),
    setPasteConfirmOpen: paste.setPasteConfirmOpen,
    setPastePendingPaths: paste.setPastePendingPaths,
    setPasteConflicts: paste.setPasteConflicts,
    setPasteConfirmIndex: paste.setPasteConfirmIndex,
    getDeleteTargets: () => resolve(state.deleteTargets),
    setDeleteConfirmOpen: deleteSet.setDeleteConfirmOpen,
    setDeleteTargets: deleteSet.setDeleteTargets,
    setDeleteError: deleteSet.setDeleteError,
    getDeleteModalEl: refs.getDeleteModalEl,
    getRenameTarget: () => resolve(state.renameTarget),
    getRenameValue: () => resolve(state.renameValue),
    setRenameTarget: rename.setRenameTarget,
    setRenameValue: rename.setRenameValue,
    setRenameError: rename.setRenameError,
    setRenameOpen: rename.setRenameOpen,
    getRenameInputEl: refs.getRenameInputEl,
    getRenameModalEl: refs.getRenameModalEl,
    setCreateType: create.setCreateType,
    getCreateType: () => resolve(state.createType),
    getCreateName: () => resolve(state.createName),
    setCreateName: create.setCreateName,
    setCreateError: create.setCreateError,
    setCreateOpen: create.setCreateOpen,
    getCreateInputEl: refs.getCreateInputEl,
    getCreateModalEl: refs.getCreateModalEl,
    getJumpUrlValue: () => resolve(state.jumpUrlValue),
    setJumpUrlOpen: jump.setJumpUrlOpen,
    setJumpUrlError: jump.setJumpUrlError,
    setJumpUrlValue: jump.setJumpUrlValue,
    getJumpUrlInputEl: refs.getJumpUrlInputEl,
    getJumpUrlModalEl: refs.getJumpUrlModalEl,
    getJumpList: () => resolve(state.jumpList),
    setJumpList: jump.setJumpList,
    getPathHistory: () => resolve(state.pathHistory),
    setPathHistory: jump.setPathHistory,
    getSearchQuery: () => resolve(state.searchQuery),
    setSearchQuery: search.setSearchQuery,
    setSearchActive: search.setSearchActive,
    setSearchError: search.setSearchError,
    getSearchHistory: () => resolve(state.searchHistory),
    setSearchHistory: search.setSearchHistory,
    scheduleUiSave: deps.scheduleUiSave,
    getExternalAppAssociations: () => resolve(state.externalAppAssociations),
    getExternalAppsRaw: () => resolve(state.externalApps),
    getUiLanguage: () => resolve(state.ui_language),
    setAboutOpen: about.setAboutOpen,
    setFocusedIndex: selection.setFocusedIndex,
    setSelected: selection.setSelected,
    getContextMenuOpen: () => resolve(state.contextMenuOpen),
    setContextMenuOpen: contextMenu.setContextMenuOpen,
    getContextMenuPos: () => resolve(state.contextMenuPos),
    setContextMenuPos: contextMenu.setContextMenuPos,
    setContextMenuMode: contextMenu.setContextMenuMode,
    getContextMenuMode: () => resolve(state.contextMenuMode),
    setContextMenuCanPaste: contextMenu.setContextMenuCanPaste,
    getContextMenuCanPaste: () => resolve(state.contextMenuCanPaste),
    setContextMenuIndex: contextMenu.setContextMenuIndex,
    getContextMenuIndex: () => resolve(state.contextMenuIndex),
    getContextMenuEl: refs.getContextMenuEl,
    getLastClipboard: () => resolve(state.lastClipboard),
    getDropdownEl: refs.getDropdownEl,
    setDropdownOpen: dropdown.setDropdownOpen,
    getStatusMessage: () => resolve(state.statusMessage),
    setStatusMessageState: status.setStatusMessageState,
    getStatusTimer: () => resolve(state.statusTimer),
    setStatusTimer: status.setStatusTimer,
    setError: failure.setError,
    setFailureModalOpen: failure.setFailureModalOpen,
    setFailureModalTitle: failure.setFailureModalTitle,
    setFailureItems: failure.setFailureItems,
    setLastClipboard: clipboard.setLastClipboard,
    setPasteMode: paste.setPasteMode,
    setPasteApplyAll: paste.setPasteApplyAll,
    loadDir: deps.loadDir,
    getCurrentPath: () => resolve(state.currentPath),
    getEntries: () => resolve(state.entries),
    getFocusedIndex: () => resolve(state.focusedIndex),
    getSelectedPaths: () => resolve(state.selectedPaths),
    setUndoStack: undo.setUndoStack,
    getUndoStack: () => resolve(state.undoStack),
    setRedoStack: undo.setRedoStack,
    getRedoStack: () => resolve(state.redoStack),
    undoLimit: deps.undoLimit,
    moveFocusByRow: deps.moveFocusByRow,
    setDeleteConfirmIndex: deleteSet.setDeleteConfirmIndex,
    setZipMode: zip.setZipMode,
    getZipMode: () => resolve(state.zipMode),
    setZipTargets: zip.setZipTargets,
    getZipTargets: () => resolve(state.zipTargets),
    setZipDestination: zip.setZipDestination,
    getZipDestination: () => resolve(state.zipDestination),
    setZipPassword: zip.setZipPassword,
    getZipPassword: () => resolve(state.zipPassword),
    setZipError: zip.setZipError,
    setZipPasswordAttempts: zip.setZipPasswordAttempts,
    getZipPasswordAttempts: () => resolve(state.zipPasswordAttempts),
    setZipConfirmIndex: zip.setZipConfirmIndex,
    setZipOverwriteConfirmed: zip.setZipOverwriteConfirmed,
    getZipOverwriteConfirmed: () => resolve(state.zipOverwriteConfirmed),
    setZipModalOpen: zip.setZipModalOpen,
    setAnchorIndex: selection.setAnchorIndex,
    zipPasswordMaxAttempts: deps.zipPasswordMaxAttempts,
  };
}

