  export const SORT_MENU_KEYS = ["name", "size", "type", "modified"] as const;

  export const KEYMAP_ACTIONS = [
    { id: "move_up", labelKey: "action.move_up" },
    { id: "move_down", labelKey: "action.move_down" },
    { id: "move_left", labelKey: "action.move_left" },
    { id: "move_right", labelKey: "action.move_right" },
    { id: "page_up", labelKey: "action.page_up" },
    { id: "page_down", labelKey: "action.page_down" },
    { id: "undo", labelKey: "action.undo" },
    { id: "redo", labelKey: "action.redo" },
    { id: "select_toggle", labelKey: "action.select_toggle" },
    { id: "select_all", labelKey: "action.select_all" },
    { id: "clear_selection", labelKey: "action.clear_selection" },
    { id: "open", labelKey: "action.open" },
    { id: "go_parent", labelKey: "action.go_parent" },
    { id: "exit", labelKey: "action.exit" },
    { id: "settings", labelKey: "action.settings" },
    { id: "help_keymap", labelKey: "action.help_keymap" },
    { id: "focus_path", labelKey: "action.focus_path" },
    { id: "toggle_hidden", labelKey: "action.toggle_hidden" },
    { id: "toggle_tree", labelKey: "action.toggle_tree" },
    { id: "copy", labelKey: "action.copy" },
    { id: "duplicate", labelKey: "action.duplicate" },
    { id: "prefix_date", labelKey: "action.prefix_date" },
    { id: "cut", labelKey: "action.cut" },
    { id: "paste", labelKey: "action.paste" },
    { id: "delete", labelKey: "action.delete" },
    { id: "rename", labelKey: "action.rename" },
    { id: "new_file", labelKey: "action.new_file" },
    { id: "properties", labelKey: "action.properties" },
    { id: "refresh", labelKey: "action.refresh" },
    { id: "search", labelKey: "action.search" },
    { id: "sort_menu", labelKey: "action.sort_menu" },
    { id: "history_jump_list", labelKey: "action.history_jump_list" },
    { id: "jump_add", labelKey: "action.jump_add" },
    { id: "jump_add_url", labelKey: "action.jump_add_url" },
    { id: "history", labelKey: "action.history" },
    { id: "toggle_size", labelKey: "action.toggle_size" },
    { id: "toggle_time", labelKey: "action.toggle_time" },
    { id: "open_explorer", labelKey: "action.open_explorer" },
    { id: "open_cmd", labelKey: "action.open_cmd" },
    { id: "open_terminal_cmd", labelKey: "action.open_terminal_cmd" },
    { id: "open_terminal_powershell", labelKey: "action.open_terminal_powershell" },
    { id: "open_terminal_wsl", labelKey: "action.open_terminal_wsl" },
    { id: "open_vscode", labelKey: "action.open_vscode" },
    { id: "open_git_client", labelKey: "action.open_git_client" },
    { id: "zip_create", labelKey: "action.zip_create" },
    { id: "zip_extract", labelKey: "action.zip_extract" },
  ] as const;

  export const KEYMAP_DEFAULTS = {
      windows: {
        move_up: "ArrowUp",
        move_down: "ArrowDown",
        move_left: "ArrowLeft",
        move_right: "ArrowRight",
        page_up: "PageUp",
        page_down: "PageDown",
        undo: "Ctrl+Z",
        redo: "Ctrl+Shift+Z",
        select_toggle: "Space",
      select_all: "Ctrl+A",
      clear_selection: "Escape",
      open: "Enter",
      go_parent: "Backspace",
      exit: "Ctrl+Q",
      settings: "Ctrl+,",
      help_keymap: "F1",
      focus_path: "Ctrl+L",
      toggle_hidden: "Ctrl+H",
      toggle_tree: "Ctrl+Shift+B",
      copy: "Ctrl+C",
      duplicate: "Ctrl+D",
      prefix_date: "Ctrl+Shift+D",
      cut: "Ctrl+X",
      paste: "Ctrl+V",
      delete: "Delete",
      rename: "F2",
      new_file: "Ctrl+N",
      properties: "Alt+Enter",
      refresh: "F5",
      search: "/",
      sort_menu: "S",
      history_jump_list: "Ctrl+J",
      jump_add: "Ctrl+Shift+J",
      jump_add_url: "Ctrl+Shift+U",
      history: "Ctrl+Y",
      toggle_size: "Ctrl+Shift+S",
      toggle_time: "Ctrl+Shift+T",
      open_explorer: "Ctrl+Alt+E",
      open_cmd: "Ctrl+Alt+C",
      open_terminal_cmd: "Ctrl+Alt+1",
      open_terminal_powershell: "Ctrl+Alt+2",
      open_terminal_wsl: "Ctrl+Alt+3",
      open_vscode: "Ctrl+Alt+V",
      open_git_client: "Ctrl+Alt+Shift+G",
      zip_create: "Ctrl+Alt+Z",
      zip_extract: "Ctrl+Alt+X",
    },
      vim: {
        move_up: "K",
        move_down: "J",
        move_left: "H",
        move_right: "L",
        page_up: "Ctrl+U",
        page_down: "Ctrl+D",
        undo: "U",
        redo: "Ctrl+R",
        select_toggle: "Space",
      select_all: "Ctrl+A",
      clear_selection: "Escape",
      open: "Enter",
      go_parent: "Backspace",
      exit: "Ctrl+Q",
      settings: "Ctrl+,",
      help_keymap: "F1",
      focus_path: ":",
      toggle_hidden: "Ctrl+H",
      toggle_tree: "Ctrl+Shift+B",
      copy: "Y",
      duplicate: "Shift+Y",
      prefix_date: "Shift+D",
      cut: "X",
      paste: "P",
      delete: "D",
      rename: "F2",
      new_file: "Ctrl+N",
      properties: "P",
      refresh: "R",
      search: "/",
      sort_menu: "S",
      history_jump_list: "Ctrl+J",
      jump_add: "Ctrl+Shift+J",
      jump_add_url: "Ctrl+Shift+U",
      history: "Ctrl+Y",
      toggle_size: "Ctrl+Shift+S",
      toggle_time: "Ctrl+Shift+T",
      open_explorer: "Ctrl+Alt+E",
      open_cmd: "Ctrl+Alt+C",
      open_terminal_cmd: "Ctrl+Alt+1",
      open_terminal_powershell: "Ctrl+Alt+2",
      open_terminal_wsl: "Ctrl+Alt+3",
      open_vscode: "Ctrl+Alt+V",
      open_git_client: "Ctrl+Alt+Shift+G",
      zip_create: "Z",
      zip_extract: "Shift+Z",
    },
  };

  export const STRINGS = {
    en: {
      "menu.file": "File",
      "menu.edit": "Edit",
      "menu.view": "View",
      "menu.navigate": "Navigate",
      "menu.help": "Help",
      "menu.open": "Open",
      "menu.open_parent": "Open Parent",
      "menu.open_explorer": "Open in Explorer",
      "menu.open_cmd": "Open in Terminal",
      "menu.open_vscode": "Open in VS Code",
      "menu.open_git_client": "Open in Git Client",
      "menu.undo": "Undo",
      "menu.redo": "Redo",
      "menu.copy": "Copy",
      "menu.duplicate": "Duplicate",
      "menu.prefix_date": "Add Date Prefix",
      "menu.cut": "Cut",
      "menu.paste": "Paste",
      "menu.delete": "Delete",
      "menu.properties": "Properties",
      "menu.exit": "Exit",
      "menu.select_all": "Select All",
      "menu.clear_selection": "Clear Selection",
      "menu.invert_selection": "Invert Selection",
      "menu.find": "Find",
      "menu.settings": "Settings...",
      "menu.sort": "Sort...",
      "menu.ui_show_hidden": "Show Hidden",
      "menu.ui_show_tree": "Tree View",
      "menu.ui_theme": "ui_theme",
      "menu.refresh": "Refresh",
      "menu.back": "Back",
      "menu.forward": "Forward",
      "menu.history_jump_list": "Jump List...",
      "menu.history": "History...",
      "menu.jump_add": "Add to Jump List",
      "menu.jump_add_url": "Add URL to Jump List",
      "menu.keymap": "Keymap",
      "menu.user_manual": "User Manual",
      "menu.about": "About",
      "menu.help_unavailable": "Help not available",
      "about.title": "About ReflexFiles",
      "about.homepage": "Homepage",
      "about.license": "License",
      "about.version": "Version",
      "about.close": "Close",
      "status.opened_config": "Opened config file",
      "status.open_failed": "Failed to open",
      "action.move_up": "Move Up",
      "action.move_down": "Move Down",
      "action.move_left": "Move Left",
      "action.move_right": "Move Right",
      "action.page_up": "Page Up",
      "action.page_down": "Page Down",
      "action.undo": "Undo",
      "action.redo": "Redo",
      "action.select_toggle": "Select Toggle",
      "action.select_all": "Select All",
      "action.clear_selection": "Clear Selection",
      "action.open": "Open",
      "action.go_parent": "Parent Folder",
      "action.exit": "Exit",
      "action.settings": "Settings",
      "action.help_keymap": "Keymap",
      "action.focus_path": "Focus PATH",
      "action.toggle_hidden": "Toggle Hidden",
      "action.toggle_tree": "Toggle Tree View",
      "action.copy": "Copy",
      "action.duplicate": "Duplicate",
      "action.prefix_date": "Add Date Prefix",
      "action.cut": "Cut",
      "action.paste": "Paste",
      "action.delete": "Delete",
      "action.rename": "Rename",
      "action.new_file": "New File",
      "action.properties": "Properties",
      "action.refresh": "Refresh",
      "action.search": "Search",
      "action.sort_menu": "Sort Menu",
      "action.history_jump_list": "Jump List",
      "action.jump_add": "Add to Jump List",
      "action.jump_add_url": "Add URL to Jump List",
      "action.history": "History",
      "action.toggle_size": "Toggle Size",
      "action.toggle_time": "Toggle Time",
      "action.open_explorer": "Open in Explorer",
      "action.open_cmd": "Open in Terminal",
      "action.open_terminal_cmd": "Open CMD Terminal",
      "action.open_terminal_powershell": "Open PowerShell Terminal",
      "action.open_terminal_wsl": "Open WSL Terminal",
      "action.open_vscode": "Open in VS Code",
      "action.open_git_client": "Open in Git Client",
      "action.zip_create": "Compress to ZIP",
      "action.zip_extract": "Extract ZIP",
      "state.on": "On",
      "state.off": "Off",
      "state.light": "Light",
      "state.dark": "Dark",
      "search.label": "Search",
      "search.placeholder": "Search...",
      "search.regex": "Regex",
      "search.apply": "Apply",
      "search.clear": "Clear",
      "search.invalid_regex": "Invalid regular expression",
      "sort.name": "Name",
      "sort.size": "Size",
      "sort.type": "Type",
      "sort.modified": "Modified",
      "delete.title": "Delete to Recycle Bin",
      "delete.single": "Move \"{name}\" to Recycle Bin?",
      "delete.multi": "Move {count} items to Recycle Bin?",
      "delete.button": "Delete",
      "cancel": "Cancel",
      "paste.title": "Name conflict",
      "paste.body": "{count} item(s) already exist in the destination.",
      "paste.empty_clipboard": "Clipboard has no files",
      "paste.nothing": "Nothing to paste",
      "paste.apply_all": "Apply to all",
      "paste.overwrite": "Overwrite",
      "paste.skip": "Skip",
      "create.title": "New",
      "create.type": "Type",
      "create.file": "File",
      "create.folder": "Folder",
      "create.name": "Name",
      "create.button": "Create",
      "jump_url.title": "Add URL to Jump List",
      "jump_url.label": "URL",
      "jump_url.placeholder": "https://example.com",
      "jump_url.add": "Add",
      "rename.title": "Rename",
      "rename.name": "New name",
      "rename.button": "Rename",
      "error.url_invalid": "Invalid URL",
      "properties.title": "Properties",
      "properties.name": "Name",
      "properties.path": "Path",
      "properties.type": "Type",
      "properties.size": "Size",
      "properties.created": "Created",
      "properties.modified": "Modified",
      "properties.accessed": "Accessed",
      "properties.hidden": "Hidden",
      "properties.readonly": "Read-only",
      "properties.system": "System",
      "properties.extension": "Extension",
      "properties.files": "Files",
      "properties.folders": "Folders",
      "properties.calc": "Calculating...",
      "properties.timeout": "Timeout",
      "properties.yes": "Yes",
      "properties.no": "No",
      "properties.timeout_label": "Timeout (ms)",
      "properties.clear_cache": "Clear Cache",
      "properties.retry": "Retry",
      "properties.cancel_calc": "Cancel Calc",
      "close": "Close",
      "expand": "Expand",
      "collapse": "Collapse",
      "settings.title": "Settings",
      "settings.appearance": "Appearance",
      "settings.ui_theme": "ui_theme",
      "settings.on": "On",
      "settings.off": "Off",
      "settings.behavior": "Behavior",
      "settings.ui_language": "ui_language",
      "settings.language_en": "English",
      "settings.language_ja": "Japanese",
      "settings.file_icon_mode": "File Icons",
      "settings.file_icon_mode_by_type": "By type",
      "settings.file_icon_mode_simple": "Simple",
      "settings.file_icon_mode_none": "None",
      "settings.keymap": "Keymap",
      "settings.input_keymap_custom": "Key Bindings (Custom)",
      "settings.keymap_help":
        "Click a field and press keys. Empty disables. Reset restores default.",
      "settings.keymap_filter": "Filter actions...",
      "settings.keymap_custom_only": "Custom only",
      "settings.reset_all": "Reset All",
      "settings.disable_all": "Disable All",
      "settings.reset": "Reset",
      "settings.disable": "Disable",
      "settings.disabled": "Disabled",
      "settings.conflict": "Conflict",
      "settings.ui_show_hidden": "Show Hidden",
      "settings.ui_show_size": "Show Size",
      "settings.ui_show_time": "Show Time",
      "settings.default_sort": "Default Sort",
      "settings.asc": "Asc",
      "settings.desc": "Desc",
      "settings.dir_stats_timeout": "Dir stats timeout (ms)",
      "settings.logging": "Logging",
      "settings.logging_label": "Logging",
      "settings.log_path": "Log file",
      "settings.section.general": "General",
      "settings.section.external": "External Tools",
      "settings.section.advanced": "Advanced",
      "settings.help.general": "Basic behavior and appearance.",
      "settings.help.external": "Tools and terminal profile names used by shortcuts.",
      "settings.help.advanced": "Advanced operations and direct config editing.",
      "settings.desc.theme": "Applies immediately.",
      "settings.desc.language": "Applies immediately.",
      "settings.desc.file_icon_mode": "Choose by-type icons, simple icons, or hide icons.",
      "settings.desc.dir_stats_timeout": "Minimum 500ms. Larger values reduce timeout errors.",
      "settings.external_terminal_profile": "Terminal profile (default)",
      "settings.external_terminal_profile_cmd": "Terminal profile for Ctrl+Alt+1 (CMD)",
      "settings.external_terminal_profile_powershell": "Terminal profile for Ctrl+Alt+2 (PowerShell)",
      "settings.external_terminal_profile_wsl": "Terminal profile for Ctrl+Alt+3 (WSL)",
      "settings.external_vscode_path": "VS Code executable path",
      "settings.external_git_client_path": "Git client executable path",
      "settings.desc.external_terminal_profile": "Used when specific profile is not set.",
      "settings.desc.external_terminal_profile_cmd": "Exact Windows Terminal profile name.",
      "settings.desc.external_terminal_profile_powershell": "Exact Windows Terminal profile name.",
      "settings.desc.external_terminal_profile_wsl": "Exact Windows Terminal profile name.",
      "settings.desc.external_vscode_path": "If empty, PATH resolution is used.",
      "settings.desc.external_git_client_path": "Required for Open in Git Client.",
      "settings.external_diagnostics": "Launch diagnostics",
      "settings.test_terminal": "Test Terminal",
      "settings.test_vscode": "Test VS Code",
      "settings.test_git_client": "Test Git Client",
      "settings.test_running": "Testing...",
      "settings.test_path_missing": "Open a folder first, then run diagnostics.",
      "settings.test_ok": "{target}: launch command sent.",
      "settings.test_failed": "{target}: {error}",
      "settings.placeholder.profile_default": "Use Windows Terminal default",
      "settings.placeholder.profile_cmd": "e.g. Command Prompt",
      "settings.placeholder.profile_powershell": "e.g. PowerShell",
      "settings.placeholder.profile_wsl": "e.g. Ubuntu",
      "settings.open_config_file": "Open config.toml",
      "settings.detected_profiles": "Detected Windows Terminal profiles",
      "settings.default_profile_badge": "Default",
      "settings.no_profiles": "No profile information found.",
      "settings.export_diagnostic_report": "Export Diagnostic Report",
      "settings.desc.export_diagnostic_report": "Writes environment/config/log summary for troubleshooting.",
      "settings.report_running": "Generating report...",
      "settings.report_ok": "Report saved: {path}",
      "settings.report_failed": "Report generation failed: {error}",
      "settings.report_ready": "Diagnostic report generated",
      "settings.report_ok_copied": "Report saved and path copied: {path}",
      "settings.report_option_mask_paths": "Mask sensitive paths",
      "settings.report_option_zip": "Save as ZIP",
      "settings.report_option_copy_path": "Copy output path to clipboard",
      "settings.report_option_open_after": "Open after export",
      "settings.create_backup": "Create Config Backup",
      "settings.restore_latest_backup": "Restore Latest Backup",
      "settings.backup_ok": "Backup created: {path}",
      "settings.backup_failed": "Backup failed: {error}",
      "settings.backup_ready": "Config backup created",
      "settings.restore_ok": "Latest backup restored.",
      "settings.restore_failed": "Restore failed: {error}",
      "settings.restore_ready": "Config restored from backup",
      "settings.restore_confirm": "Restore latest config backup? Current config will be overwritten.",
      "settings.gdrive.title": "Google Drive (Phased Preview)",
      "settings.gdrive.help":
        "Personal-use setup only. Keep real credentials out of the public repository.",
      "settings.gdrive.persist_notice":
        "Saved locally: client_id, redirect_uri, account ID. client_secret is stored only in OS secure credential storage (not in config.toml). callback URL is not saved.",
      "settings.gdrive.phase": "Auth phase",
      "settings.gdrive.phase_signed_out": "Signed out",
      "settings.gdrive.phase_pending": "Pending callback",
      "settings.gdrive.phase_authorized": "Authorized",
      "settings.gdrive.backend_mode": "Backend mode",
      "settings.gdrive.backend_mode_stub": "Stub (virtual test data)",
      "settings.gdrive.backend_mode_real": "Real Google Drive API",
      "settings.gdrive.account_id_current": "Current account",
      "settings.gdrive.granted_scopes": "Granted scopes",
      "settings.gdrive.refresh_persisted": "Refresh token persisted",
      "settings.gdrive.token_store": "Token store backend",
      "settings.gdrive.token_store_available": "Token store available",
      "settings.gdrive.last_error": "Last auth error",
      "settings.gdrive.refresh_status": "Refresh Auth Status",
      "settings.gdrive.sign_out": "Sign Out",
      "settings.gdrive.client_id": "OAuth client_id",
      "settings.gdrive.client_id_help": "Paste your own Google OAuth desktop client ID.",
      "settings.gdrive.client_secret_optional": "OAuth client_secret (optional)",
      "settings.gdrive.client_secret_help":
        "Only needed if Google requires it during token exchange. If entered and sign-in succeeds, it is stored in OS secure credential storage. Never commit real secrets.",
      "settings.gdrive.redirect_uri": "OAuth redirect_uri",
      "settings.gdrive.redirect_uri_help": "Must match redirect URI configured in your Google Cloud client.",
      "settings.gdrive.start_sign_in": "Start Sign-In",
      "settings.gdrive.callback_url": "Callback URL",
      "settings.gdrive.callback_url_help":
        "Paste the full callback URL after browser sign-in (contains state and code).",
      "settings.gdrive.account_id": "Account ID (email)",
      "settings.gdrive.account_id_help": "Google account email used for this authorization.",
      "settings.gdrive.refresh_token_optional": "Refresh token (optional)",
      "settings.gdrive.refresh_token_help":
        "Optional manual mode. Leave empty for automatic token exchange.",
      "settings.gdrive.complete_sign_in": "Complete Sign-In",
      "settings.gdrive.placeholder_client_id":
        "1234567890-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
      "settings.gdrive.placeholder_redirect_uri": "http://127.0.0.1:45123/oauth2/callback",
      "settings.gdrive.placeholder_callback_url":
        "http://127.0.0.1:45123/oauth2/callback?state=...&code=...",
      "settings.gdrive.placeholder_account_id": "user@example.com",
      "settings.gdrive.busy": "Google Drive auth operation in progress...",
      "settings.gdrive.callback_missing": "Callback URL is required.",
      "settings.gdrive.callback_parse_error":
        "Callback URL must contain both state and code query parameters.",
      "settings.gdrive.token_exchange_network_error":
        "Network error while contacting Google token endpoint.",
      "settings.gdrive.token_exchange_failed": "Google token exchange failed.",
      "settings.gdrive.token_exchange_failed_with_detail":
        "Google token exchange failed: {detail}",
      "settings.gdrive.token_exchange_requires_client_secret":
        'Google requested client_secret. Set "OAuth client_secret (optional)" then retry Complete Sign-In.',
      "settings.gdrive.token_exchange_no_access_token":
        "Google token response did not include access_token.",
      "settings.gdrive.client_or_redirect_required": "client_id and redirect_uri are required.",
      "settings.gdrive.account_required": "Account ID is required.",
      "settings.gdrive.started_opened": "OAuth session started. Browser opened for sign-in.",
      "settings.gdrive.callback_auto_captured":
        "Callback URL captured automatically. Review account/secret fields and run Complete Sign-In.",
      "settings.gdrive.complete_done": "Google Drive auth session updated.",
      "settings.gdrive.complete_done_manual":
        "Google Drive auth session updated (manual token mode).",
      "settings.gdrive.sign_out_done": "Google Drive auth session cleared.",
      "settings.gdrive.stub_notice":
        "This build uses stub data for gdrive:// paths. Real Google Drive file listing is not active yet.",
      "settings.shortcut_conflicts": "Shortcut conflicts",
      "settings.no_shortcut_conflicts": "No known global shortcut conflicts detected.",
      "settings.shortcut_conflict_google_drive": "May trigger Google Drive global shortcut.",
      "settings.shortcut_conflict_task_manager": "Conflicts with Windows Task Manager shortcut.",
      "settings.shortcut_conflict_input_switch": "May conflict with input language switch shortcut.",
      "settings.shortcut_conflict_display_driver": "May conflict with display driver hotkeys.",
      "settings.shortcut_conflict_item": "{binding} ({action}): {reason}",
      "settings.shortcut_conflict_internal_item": "{binding}: assigned to multiple actions ({actions}).",
      "settings.save": "Save",
      "settings.saved": "Settings saved",
      "settings.no_changes": "No settings changes",
      "settings.validation_invalid_theme": "Theme value is invalid.",
      "settings.validation_invalid_language": "Language value is invalid.",
      "settings.validation_invalid_icon_mode": "File icon mode value is invalid.",
      "settings.validation_timeout_range": "Dir stats timeout must be between 500 and 3,600,000 ms.",
      "settings.validation_path_too_long": "Executable path is too long.",
      "settings.validation_profile_too_long": "Terminal profile name is too long.",
      "settings.validation_single_line": "Line breaks are not allowed in settings values.",
      "zip.title_create": "Compress to ZIP",
      "zip.title_extract": "Extract ZIP",
      "zip.items": "Items: {count}",
      "zip.file": "File: {file}",
      "zip.attempts": "Attempts: {count}/{total}",
      "zip.destination": "Destination",
      "zip.password": "Password (optional)",
      "zip.overwrite_confirm": "I understand that existing files may be overwritten",
      "zip.create": "Create",
      "zip.extract": "Extract",
      "failure.title": "Operation failed",
      "failure.body": "{count} item(s) failed.",
      "failure.code.invalid_path": "Invalid path",
      "failure.code.invalid_name": "Invalid name",
      "failure.code.invalid_kind": "Invalid type",
      "failure.code.parent_not_found": "Parent not found",
      "failure.code.destination_not_found": "Destination not found",
      "failure.code.destination_not_dir": "Destination is not a directory",
      "failure.code.destination_inside_source": "Destination is inside source",
      "failure.code.no_items": "No items",
      "failure.code.same_path": "Source and destination are the same",
      "failure.code.not_found": "Not found",
      "failure.code.permission_denied": "Permission denied",
      "failure.code.already_exists": "Already exists",
      "failure.code.invalid_input": "Invalid input",
      "failure.code.io_error": "I/O error",
      "failure.code.canceled": "Canceled",
      "failure.code.conflict": "Conflict",
      "failure.code.unknown": "Unknown error",
      "failure.code.undo_unavailable": "Undo not possible",
      "failure.code.redo_unavailable": "Redo not possible",
      "loading": "Loading...",
      "no_items": "No items",
      "context.new": "New...",
      "context.open": "Open",
      "context.open_explorer": "Open in Explorer",
      "context.open_cmd": "Open in Terminal",
      "context.open_vscode": "Open in VS Code",
      "context.open_git_client": "Open in Git Client",
      "context.gdrive_write_back": "Write Back to Google Drive",
      "context.open_parent": "Open Parent",
      "context.copy": "Copy",
      "context.duplicate": "Duplicate",
      "context.prefix_date": "Add Date Prefix",
      "context.cut": "Cut",
      "context.paste": "Paste",
      "context.delete": "Delete",
      "context.rename": "Rename",
      "context.properties": "Properties",
      "context.compress": "Compress to ZIP",
      "context.extract": "Extract ZIP",
      "capability.not_available": "Not available for this provider",
      "status.no_selection": "No selection",
      "status.copied": "Copied {count} item(s)",
      "status.duplicated": "Duplicated {count} item(s)",
      "status.prefix_date_failed": "Date prefix failed",
      "status.prefixed_date": "Added date prefix to {count} item(s)",
      "status.duplicate_failed": "Duplicate failed",
      "status.cut": "Cut {count} item(s)",
      "status.copying": "Copying",
      "status.moving": "Moving",
      "status.undo_done": "Undid last action",
      "status.undo_failed": "Undo failed",
      "status.redo_done": "Redid last action",
      "status.redo_failed": "Redo failed",
      "status.undo_empty": "Nothing to undo",
      "status.redo_empty": "Nothing to redo",
      "status.failed": "Failed {name}{reason}",
      "status.done": "{label} {name} ({index}/{total})",
      "status.selected": "Sel: {count}",
      "status.focus": "Focus: {target}",
      "status.hidden": "Hidden: {state}",
      "status.filter": "Filter: \"{query}\"",
      "status.keymap_hint": "F1: Keymap",
      "status.cache_cleared": "Dir stats cache cleared",
      "status.selection_cleared": "Selection cleared",
      "status.no_parent": "No parent",
      "status.same_path": "Skipped: source and destination are the same",
      "status.jump_added": "Added to jump list",
      "status.gdrive_workcopy_opened":
        "Opened local workcopy for Google Drive file: {name} (not uploaded automatically)",
      "status.gdrive_writeback_only": "Write-back is available only for Google Drive files.",
      "status.gdrive_workcopy_missing":
        "No local workcopy found for {name}. Open it in an external app first.",
      "status.gdrive_writeback_done": "Uploaded local workcopy to Google Drive: {name}",
      "status.gdrive_writeback_no_change": "No local changes to upload: {name}",
      "status.gdrive_writeback_conflict":
        "Upload blocked by conflict on Google Drive: {name}",
      "status.gdrive_writeback_unknown":
        "Write-back finished with unknown result: {name}",
      "focus.list": "List",
      "focus.tree": "Tree",
      "focus.path": "Path",
      "focus.menu": "Menu",
      "focus.context": "Context Menu",
      "focus.dropdown": "Dropdown",
      "focus.modal": "Modal",
      "focus.none": "None",
      "duplicate.suffix": " - Copy",
      "prefix_date.skipped": "Skipped {count} item(s)",
      "error.delete_failed": "Delete failed",
      "error.rename_failed": "Rename failed",
      "error.create_failed": "Create failed",
      "error.name_required": "Name is required",
      "error.no_current_path": "Current path is not available",
      "error.no_associated_app": "No external app is associated with this file",
      "error.open_explorer_failed": "Failed to open in Explorer: {error}",
      "error.open_cmd_failed": "Failed to open terminal: {error}",
      "error.open_vscode_failed": "Failed to open in VS Code: {error}",
      "error.open_git_failed": "Failed to open in Git client: {error}",
      "zip.error_destination_required": "Destination is required",
      "zip.error_overwrite_confirm": "Please confirm overwrite before extracting",
      "zip.error_password_attempts_exceeded": "Password attempts exceeded",
      "zip.error_password_failed": "Password failed 3 times",
      "zip.error_invalid_password": "Invalid password ({count}/{total})",
      "history.clear_confirm": "Clear history?",
      "history.delete": "Del",
      "label.path": "PATH",
      "label.list": "File List",
      "list.gdrive_workcopy_local": "Local Google Drive workcopy exists",
      "list.gdrive_workcopy_dirty": "Local changes pending upload to Google Drive",
      "label.tree": "Tree View",
      "keymap.windows_like": "Windows-like",
      "keymap.vim_like": "Vim-like",
    },
    ja: {
      "menu.file": "ファイル",
      "menu.edit": "編集",
      "menu.view": "表示",
      "menu.navigate": "移動",
      "menu.help": "ヘルプ",
      "menu.open": "開く",
      "menu.open_parent": "親フォルダを開く",
      "menu.open_explorer": "エクスプローラーで開く",
      "menu.open_cmd": "ターミナルを開く",
      "menu.open_vscode": "VS Codeで開く",
      "menu.open_git_client": "Gitクライアントで開く",
      "menu.undo": "元に戻す",
      "menu.redo": "やり直し",
      "menu.copy": "コピー",
      "menu.duplicate": "複製",
      "menu.prefix_date": "日付プレフィックス追加",
      "menu.cut": "カット",
      "menu.paste": "ペースト",
      "menu.delete": "削除",
      "menu.properties": "プロパティ",
      "menu.exit": "終了",
      "menu.select_all": "すべて選択",
      "menu.clear_selection": "選択解除",
      "menu.invert_selection": "選択反転",
      "menu.find": "検索",
      "menu.settings": "設定...",
      "menu.sort": "並び替え...",
      "menu.ui_show_hidden": "隠しファイル",
      "menu.ui_show_tree": "ツリービュー",
      "menu.ui_theme": "テーマ",
      "menu.refresh": "更新",
      "menu.back": "戻る",
      "menu.forward": "進む",
      "menu.history_jump_list": "ジャンプリスト...",
      "menu.history": "履歴...",
      "menu.jump_add": "ジャンプリストに追加",
      "menu.jump_add_url": "URLをジャンプリストに追加",
      "menu.keymap": "キー一覧",
      "menu.user_manual": "ユーザーマニュアル",
      "menu.about": "About",
      "menu.help_unavailable": "ヘルプは未対応です",
      "about.title": "ReflexFiles について",
      "about.homepage": "URL",
      "about.license": "ライセンス",
      "about.version": "バージョン",
      "about.close": "閉じる",
      "status.opened_config": "設定ファイルを開きました",
      "status.open_failed": "開けませんでした",
      "action.move_up": "上へ移動",
      "action.move_down": "下へ移動",
      "action.move_left": "左へ移動",
      "action.move_right": "右へ移動",
      "action.page_up": "ページ上",
      "action.page_down": "ページ下",
      "action.undo": "元に戻す",
      "action.redo": "やり直し",
      "action.select_toggle": "選択トグル",
      "action.select_all": "すべて選択",
      "action.clear_selection": "選択解除",
      "action.open": "開く",
      "action.go_parent": "親フォルダ",
      "action.exit": "終了",
      "action.settings": "設定",
      "action.help_keymap": "キー一覧",
      "action.focus_path": "PATHにフォーカス",
      "action.toggle_hidden": "隠しファイル切替",
      "action.toggle_tree": "ツリービュー切替",
      "action.copy": "コピー",
      "action.duplicate": "複製",
      "action.prefix_date": "日付プレフィックス追加",
      "action.cut": "カット",
      "action.paste": "ペースト",
      "action.delete": "削除",
      "action.rename": "名前変更",
      "action.new_file": "新規作成",
      "action.properties": "プロパティ",
      "action.refresh": "更新",
      "action.search": "検索",
      "action.sort_menu": "並び替えメニュー",
      "action.history_jump_list": "ジャンプリスト",
      "action.jump_add": "ジャンプリストに追加",
      "action.jump_add_url": "URLをジャンプリストに追加",
      "action.history": "履歴",
      "action.toggle_size": "サイズ表示切替",
      "action.toggle_time": "時刻表示切替",
      "action.open_explorer": "エクスプローラーで開く",
      "action.open_cmd": "ターミナルを開く",
      "action.open_terminal_cmd": "CMDで開く",
      "action.open_terminal_powershell": "PowerShellで開く",
      "action.open_terminal_wsl": "WSLで開く",
      "action.open_vscode": "VS Codeで開く",
      "action.open_git_client": "Gitクライアントで開く",
      "action.zip_create": "ZIPに圧縮",
      "action.zip_extract": "ZIPを解凍",
      "state.on": "オン",
      "state.off": "オフ",
      "state.light": "ライト",
      "state.dark": "ダーク",
      "search.label": "検索",
      "search.placeholder": "検索...",
      "search.regex": "正規表現",
      "search.apply": "適用",
      "search.clear": "クリア",
      "search.invalid_regex": "正規表現が不正です",
      "sort.name": "名前",
      "sort.size": "サイズ",
      "sort.type": "種類",
      "sort.modified": "更新日時",
      "delete.title": "ゴミ箱へ削除",
      "delete.single": "「{name}」をゴミ箱に移動しますか？",
      "delete.multi": "{count}件をゴミ箱に移動しますか？",
      "delete.button": "削除",
      "cancel": "キャンセル",
      "paste.title": "同名ファイルの競合",
      "paste.body": "{count}件が既に存在します。",
      "paste.empty_clipboard": "クリップボードにファイルがありません",
      "paste.nothing": "貼り付ける項目がありません",
      "paste.apply_all": "すべてに適用",
      "paste.overwrite": "上書き",
      "paste.skip": "スキップ",
      "create.title": "新規作成",
      "create.type": "種別",
      "create.file": "ファイル",
      "create.folder": "フォルダ",
      "create.name": "名前",
      "create.button": "作成",
      "jump_url.title": "URLをジャンプリストに追加",
      "jump_url.label": "URL",
      "jump_url.placeholder": "https://example.com",
      "jump_url.add": "追加",
      "rename.title": "名前変更",
      "rename.name": "新しい名前",
      "rename.button": "変更",
      "properties.title": "プロパティ",
      "properties.name": "名前",
      "properties.path": "パス",
      "properties.type": "種類",
      "properties.size": "サイズ",
      "properties.created": "作成日時",
      "properties.modified": "更新日時",
      "properties.accessed": "アクセス日時",
      "properties.hidden": "隠し属性",
      "properties.readonly": "読み取り専用",
      "properties.system": "システム",
      "properties.extension": "拡張子",
      "properties.files": "ファイル数",
      "properties.folders": "フォルダ数",
      "properties.calc": "計算中...",
      "properties.timeout": "タイムアウト",
      "properties.yes": "はい",
      "properties.no": "いいえ",
      "properties.timeout_label": "タイムアウト(ms)",
      "properties.clear_cache": "キャッシュ削除",
      "properties.retry": "再試行",
      "properties.cancel_calc": "計算中止",
      "close": "閉じる",
      "expand": "展開",
      "collapse": "折りたたみ",
      "settings.title": "設定",
      "settings.appearance": "外観",
      "settings.ui_theme": "テーマ",
      "settings.on": "オン",
      "settings.off": "オフ",
      "settings.behavior": "動作",
      "settings.ui_language": "表示言語",
      "settings.language_en": "英語",
      "settings.language_ja": "日本語",
      "settings.file_icon_mode": "ファイルアイコン",
      "settings.file_icon_mode_by_type": "種類別",
      "settings.file_icon_mode_simple": "シンプル",
      "settings.file_icon_mode_none": "表示しない",
      "settings.keymap": "キーマップ",
      "settings.input_keymap_custom": "キー割り当て（カスタム）",
      "settings.keymap_help":
        "項目をクリックしてキーを押してください。空欄は無効、リセットで既定に戻ります。",
      "settings.keymap_filter": "操作を絞り込み...",
      "settings.keymap_custom_only": "カスタムのみ",
      "settings.reset_all": "すべてリセット",
      "settings.disable_all": "すべて無効",
      "settings.reset": "リセット",
      "settings.disable": "無効",
      "settings.disabled": "無効",
      "settings.conflict": "競合",
      "settings.ui_show_hidden": "隠しファイル",
      "settings.ui_show_size": "サイズ表示",
      "settings.ui_show_time": "時刻表示",
      "settings.default_sort": "既定の並び替え",
      "settings.asc": "昇順",
      "settings.desc": "降順",
      "settings.dir_stats_timeout": "フォルダ集計タイムアウト(ms)",
      "settings.logging": "ログ",
      "settings.logging_label": "ログ出力",
      "settings.log_path": "ログファイル",
      "settings.section.general": "全般",
      "settings.section.external": "外部ツール",
      "settings.section.advanced": "詳細",
      "settings.help.general": "基本動作と表示の設定です。",
      "settings.help.external": "ツール起動とターミナルプロファイル名を設定します。",
      "settings.help.advanced": "詳細操作と設定ファイル直接編集です。",
      "settings.desc.theme": "保存後すぐ反映されます。",
      "settings.desc.language": "保存後すぐ反映されます。",
      "settings.desc.file_icon_mode": "種類別表示・単純表示・非表示を選択できます。",
      "settings.desc.dir_stats_timeout": "最小500ms。大きい値ほどタイムアウトを減らせます。",
      "settings.external_terminal_profile": "ターミナルプロファイル（既定）",
      "settings.external_terminal_profile_cmd": "Ctrl+Alt+1（CMD）用プロファイル",
      "settings.external_terminal_profile_powershell": "Ctrl+Alt+2（PowerShell）用プロファイル",
      "settings.external_terminal_profile_wsl": "Ctrl+Alt+3（WSL）用プロファイル",
      "settings.external_vscode_path": "VS Code 実行ファイルパス",
      "settings.external_git_client_path": "Gitクライアント実行ファイルパス",
      "settings.desc.external_terminal_profile": "個別指定が空の場合に使われます。",
      "settings.desc.external_terminal_profile_cmd": "Windows Terminal の正確なプロファイル名を指定します。",
      "settings.desc.external_terminal_profile_powershell": "Windows Terminal の正確なプロファイル名を指定します。",
      "settings.desc.external_terminal_profile_wsl": "Windows Terminal の正確なプロファイル名を指定します。",
      "settings.desc.external_vscode_path": "空欄時はPATH上のcodeを使用します。",
      "settings.desc.external_git_client_path": "Gitクライアント起動に必要です。",
      "settings.external_diagnostics": "起動診断",
      "settings.test_terminal": "ターミナル診断",
      "settings.test_vscode": "VS Code診断",
      "settings.test_git_client": "Gitクライアント診断",
      "settings.test_running": "診断中...",
      "settings.test_path_missing": "先にフォルダを開いてから診断してください。",
      "settings.test_ok": "{target}: 起動コマンドを送信しました。",
      "settings.test_failed": "{target}: {error}",
      "settings.placeholder.profile_default": "Windows Terminal の既定を使用",
      "settings.placeholder.profile_cmd": "例: コマンド プロンプト",
      "settings.placeholder.profile_powershell": "例: PowerShell",
      "settings.placeholder.profile_wsl": "例: Ubuntu",
      "settings.open_config_file": "config.toml を開く",
      "settings.detected_profiles": "検出された Windows Terminal プロファイル",
      "settings.default_profile_badge": "既定",
      "settings.no_profiles": "プロファイル情報が見つかりません。",
      "settings.export_diagnostic_report": "診断レポートを出力",
      "settings.desc.export_diagnostic_report": "切り分け用に環境・設定・ログ要約を保存します。",
      "settings.report_running": "レポート生成中...",
      "settings.report_ok": "レポートを保存しました: {path}",
      "settings.report_failed": "レポート生成に失敗しました: {error}",
      "settings.report_ready": "診断レポートを生成しました",
      "settings.report_ok_copied": "レポートを保存し、出力先パスをコピーしました: {path}",
      "settings.report_option_mask_paths": "機密パスをマスクする",
      "settings.report_option_zip": "ZIPで保存する",
      "settings.report_option_copy_path": "出力先パスをクリップボードへコピー",
      "settings.report_option_open_after": "出力後に自動で開く",
      "settings.create_backup": "設定バックアップを作成",
      "settings.restore_latest_backup": "最新バックアップを復元",
      "settings.backup_ok": "バックアップを作成しました: {path}",
      "settings.backup_failed": "バックアップ作成に失敗しました: {error}",
      "settings.backup_ready": "設定バックアップを作成しました",
      "settings.restore_ok": "最新バックアップから復元しました。",
      "settings.restore_failed": "復元に失敗しました: {error}",
      "settings.restore_ready": "バックアップから設定を復元しました",
      "settings.restore_confirm": "最新の設定バックアップを復元しますか？現在の config.toml は上書きされます。",
      "settings.gdrive.title": "Google Drive（段階プレビュー）",
      "settings.gdrive.help":
        "個人利用前提の設定です。公開リポジトリに実資格情報を含めないでください。",
      "settings.gdrive.persist_notice":
        "ローカル保存: client_id / redirect_uri / アカウントID。client_secret は config.toml には保存せず、OSの安全な資格情報ストアのみに保存します。コールバックURLは保存しません。",
      "settings.gdrive.phase": "認証フェーズ",
      "settings.gdrive.phase_signed_out": "未サインイン",
      "settings.gdrive.phase_pending": "コールバック待ち",
      "settings.gdrive.phase_authorized": "認証済み",
      "settings.gdrive.backend_mode": "バックエンド種別",
      "settings.gdrive.backend_mode_stub": "スタブ（テスト用仮想データ）",
      "settings.gdrive.backend_mode_real": "実 Google Drive API",
      "settings.gdrive.account_id_current": "現在のアカウント",
      "settings.gdrive.granted_scopes": "許可スコープ",
      "settings.gdrive.refresh_persisted": "refresh token 保存済み",
      "settings.gdrive.token_store": "トークン保存バックエンド",
      "settings.gdrive.token_store_available": "トークン保存の利用可否",
      "settings.gdrive.last_error": "直近の認証エラー",
      "settings.gdrive.refresh_status": "認証状態を更新",
      "settings.gdrive.sign_out": "サインアウト",
      "settings.gdrive.client_id": "OAuth クライアント ID",
      "settings.gdrive.client_id_help":
        "ご自身の Google OAuth デスクトップ クライアント ID を入力します。",
      "settings.gdrive.client_secret_optional": "OAuth クライアント シークレット（任意）",
      "settings.gdrive.client_secret_help":
        "Google 側が token 交換時に要求した場合のみ使います。入力して認証が成功すると、OSの安全な資格情報ストアへ保存します。実シークレットは絶対にコミットしないでください。",
      "settings.gdrive.redirect_uri": "OAuth リダイレクト URI",
      "settings.gdrive.redirect_uri_help":
        "Google Cloud のOAuthクライアント設定と完全一致させてください。",
      "settings.gdrive.start_sign_in": "サインイン開始",
      "settings.gdrive.callback_url": "コールバック URL",
      "settings.gdrive.callback_url_help":
        "ブラウザ認証後に取得したURL（state/code付き）を貼り付けます。",
      "settings.gdrive.account_id": "アカウント ID（メールアドレス）",
      "settings.gdrive.account_id_help": "この認証で使うGoogleアカウントのメールアドレス。",
      "settings.gdrive.refresh_token_optional": "リフレッシュ トークン（任意）",
      "settings.gdrive.refresh_token_help":
        "手動モード用です。空欄なら自動token交換を試行します。",
      "settings.gdrive.complete_sign_in": "サインイン完了",
      "settings.gdrive.placeholder_client_id":
        "1234567890-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
      "settings.gdrive.placeholder_redirect_uri": "http://127.0.0.1:45123/oauth2/callback",
      "settings.gdrive.placeholder_callback_url":
        "http://127.0.0.1:45123/oauth2/callback?state=...&code=...",
      "settings.gdrive.placeholder_account_id": "user@example.com",
      "settings.gdrive.busy": "Google Drive 認証処理を実行中です...",
      "settings.gdrive.callback_missing": "コールバックURLを入力してください。",
      "settings.gdrive.callback_parse_error":
        "コールバックURLには state と code の両方が必要です。",
      "settings.gdrive.token_exchange_network_error":
        "Google token endpoint への通信に失敗しました。",
      "settings.gdrive.token_exchange_failed": "Google token 交換に失敗しました。",
      "settings.gdrive.token_exchange_failed_with_detail":
        "Google token 交換に失敗しました: {detail}",
      "settings.gdrive.token_exchange_requires_client_secret":
        "Google 側が client_secret を要求しました。OAuth client_secret（任意）を入力して再実行してください。",
      "settings.gdrive.token_exchange_no_access_token":
        "Google token 応答に access_token が含まれていません。",
      "settings.gdrive.client_or_redirect_required":
        "client_id と redirect_uri を入力してください。",
      "settings.gdrive.account_required": "アカウントIDを入力してください。",
      "settings.gdrive.started_opened":
        "OAuth セッションを開始し、サインイン用ブラウザを開きました。",
      "settings.gdrive.callback_auto_captured":
        "コールバックURLを自動取得しました。アカウント/シークレットを確認して「サインイン完了」を実行してください。",
      "settings.gdrive.complete_done": "Google Drive 認証セッションを更新しました。",
      "settings.gdrive.complete_done_manual":
        "Google Drive 認証セッションを更新しました（手動トークンモード）。",
      "settings.gdrive.sign_out_done": "Google Drive 認証セッションを解除しました。",
      "settings.gdrive.stub_notice":
        "このビルドの gdrive:// はスタブ表示です。実 Google Drive ファイル一覧はまだ有効化されていません。",
      "settings.shortcut_conflicts": "ショートカット競合",
      "settings.no_shortcut_conflicts": "既知のグローバルショートカット競合はありません。",
      "settings.shortcut_conflict_google_drive": "Google Drive のグローバルショートカットと競合する可能性があります。",
      "settings.shortcut_conflict_task_manager": "Windows のタスクマネージャー起動キーと競合します。",
      "settings.shortcut_conflict_input_switch": "入力言語切替ショートカットと競合する可能性があります。",
      "settings.shortcut_conflict_display_driver": "ディスプレイドライバのホットキーと競合する可能性があります。",
      "settings.shortcut_conflict_item": "{binding}（{action}）: {reason}",
      "settings.shortcut_conflict_internal_item": "{binding}: 複数の操作に割り当てられています（{actions}）。",
      "settings.save": "保存",
      "settings.saved": "設定を保存しました",
      "settings.no_changes": "設定変更はありません",
      "settings.validation_invalid_theme": "テーマの値が不正です。",
      "settings.validation_invalid_language": "表示言語の値が不正です。",
      "settings.validation_invalid_icon_mode": "ファイルアイコン設定の値が不正です。",
      "settings.validation_timeout_range": "フォルダ集計タイムアウトは 500 〜 3,600,000 ms の範囲で指定してください。",
      "settings.validation_path_too_long": "実行ファイルパスが長すぎます。",
      "settings.validation_profile_too_long": "ターミナルプロファイル名が長すぎます。",
      "settings.validation_single_line": "設定値に改行は使用できません。",
      "zip.title_create": "ZIPに圧縮",
      "zip.title_extract": "ZIPを解凍",
      "zip.items": "対象: {count}件",
      "zip.file": "ファイル: {file}",
      "zip.attempts": "試行回数: {count}/{total}",
      "zip.destination": "出力先",
      "zip.password": "パスワード（任意）",
      "zip.overwrite_confirm": "既存ファイルを上書きする可能性があることを理解しました",
      "zip.create": "作成",
      "zip.extract": "解凍",
      "failure.title": "処理に失敗しました",
      "failure.body": "{count}件失敗しました。",
      "failure.code.invalid_path": "パスが不正です",
      "failure.code.invalid_name": "名前が不正です",
      "failure.code.invalid_kind": "種類が不正です",
      "failure.code.parent_not_found": "親フォルダが見つかりません",
      "failure.code.destination_not_found": "出力先が見つかりません",
      "failure.code.destination_not_dir": "出力先がフォルダではありません",
      "failure.code.destination_inside_source": "出力先が元の中にあります",
      "failure.code.no_items": "対象がありません",
      "failure.code.same_path": "同じ場所のためスキップしました",
      "failure.code.not_found": "見つかりません",
      "failure.code.permission_denied": "アクセスが拒否されました",
      "failure.code.already_exists": "すでに存在しています",
      "failure.code.invalid_input": "入力が不正です",
      "failure.code.io_error": "入出力エラー",
      "failure.code.canceled": "キャンセルしました",
      "failure.code.conflict": "競合しました",
      "failure.code.unknown": "不明なエラー",
      "failure.code.undo_unavailable": "元に戻せません",
      "failure.code.redo_unavailable": "やり直せません",
      "loading": "読み込み中...",
      "no_items": "項目なし",
      "context.new": "新規作成...",
      "context.open": "開く",
      "context.open_explorer": "エクスプローラーで開く",
      "context.open_cmd": "ターミナルを開く",
      "context.open_vscode": "VS Codeで開く",
      "context.open_git_client": "Gitクライアントで開く",
      "context.gdrive_write_back": "Google Driveへ書き戻し",
      "context.open_parent": "親フォルダを開く",
      "context.copy": "コピー",
      "context.duplicate": "複製",
      "context.prefix_date": "日付プレフィックス追加",
      "context.cut": "カット",
      "context.paste": "ペースト",
      "context.delete": "削除",
      "context.rename": "名前変更",
      "context.properties": "プロパティ",
      "context.compress": "ZIPに圧縮",
      "context.extract": "ZIPを解凍",
      "capability.not_available": "このプロバイダでは利用できません",
      "status.no_selection": "選択なし",
      "status.copied": "{count}件コピーしました",
      "status.duplicated": "{count}件複製しました",
      "status.prefix_date_failed": "日付付与に失敗しました",
      "status.prefixed_date": "{count}件に日付を付けました",
      "status.duplicate_failed": "複製に失敗しました",
      "status.cut": "{count}件カットしました",
      "status.copying": "コピー中",
      "status.moving": "移動中",
      "status.undo_done": "操作を元に戻しました",
      "status.undo_failed": "元に戻す操作に失敗しました",
      "status.redo_done": "操作をやり直しました",
      "status.redo_failed": "やり直しに失敗しました",
      "status.undo_empty": "元に戻せる操作がありません",
      "status.redo_empty": "やり直せる操作がありません",
      "status.failed": "失敗: {name}{reason}",
      "status.done": "{label} {name} ({index}/{total})",
      "status.selected": "選択: {count}",
      "status.focus": "フォーカス: {target}",
      "status.hidden": "隠し: {state}",
      "status.filter": "絞り込み: \"{query}\"",
      "status.keymap_hint": "F1: キー一覧",
      "status.cache_cleared": "統計キャッシュをクリアしました",
      "status.selection_cleared": "選択を解除しました",
      "status.no_parent": "親フォルダなし",
      "status.same_path": "同じ場所のためスキップしました",
      "status.jump_added": "ジャンプリストに追加しました",
      "status.gdrive_workcopy_opened":
        "Google Drive ファイルをローカル作業コピーで開きました: {name}（自動アップロードはされません）",
      "status.gdrive_writeback_only":
        "書き戻しは Google Drive ファイルでのみ実行できます。",
      "status.gdrive_workcopy_missing":
        "{name} のローカル作業コピーがありません。先に外部アプリで開いてください。",
      "status.gdrive_writeback_done":
        "ローカル作業コピーを Google Drive に書き戻しました: {name}",
      "status.gdrive_writeback_no_change":
        "書き戻すローカル変更がありません: {name}",
      "status.gdrive_writeback_conflict":
        "Google Drive 側の競合により書き戻しを中止しました: {name}",
      "status.gdrive_writeback_unknown":
        "書き戻し結果を確認できませんでした: {name}",
      "focus.list": "リスト",
      "focus.tree": "ツリー",
      "focus.path": "パス",
      "focus.menu": "メニュー",
      "focus.context": "コンテキスト",
      "focus.dropdown": "ドロップダウン",
      "focus.modal": "モーダル",
      "focus.none": "なし",
      "duplicate.suffix": " - コピー",
      "prefix_date.skipped": "{count}件スキップしました",
      "error.delete_failed": "削除に失敗しました",
      "error.rename_failed": "名前変更に失敗しました",
      "error.create_failed": "作成に失敗しました",
      "error.name_required": "名前を入力してください",
      "error.url_invalid": "URLが正しくありません",
      "error.no_current_path": "現在のパスが不明です",
      "error.no_associated_app": "このファイルに関連付けられた外部アプリがありません",
      "error.open_explorer_failed": "エクスプローラーで開けませんでした: {error}",
      "error.open_cmd_failed": "ターミナルを開けませんでした: {error}",
      "error.open_vscode_failed": "VS Codeで開けませんでした: {error}",
      "error.open_git_failed": "Gitクライアントで開けませんでした: {error}",
      "zip.error_destination_required": "出力先が必要です",
      "zip.error_overwrite_confirm": "上書き確認にチェックしてください",
      "zip.error_password_attempts_exceeded": "パスワード試行回数の上限に達しました",
      "zip.error_password_failed": "パスワードに3回失敗しました",
      "zip.error_invalid_password": "パスワードが違います ({count}/{total})",
      "history.clear_confirm": "履歴を削除しますか？",
      "history.delete": "削除",
      "label.path": "PATH",
      "label.list": "ファイル一覧",
      "list.gdrive_workcopy_local": "Google Drive のローカル作業コピーがあります",
      "list.gdrive_workcopy_dirty": "Google Drive へ未反映のローカル変更があります",
      "label.tree": "ツリー表示",
      "keymap.windows_like": "Windows風",
      "keymap.vim_like": "Vim風",
    },
  };

  export const MENU_GROUPS = ["file", "edit", "view", "navigate", "help"];



