/**
 * @param {object} params
 * @param {object} params.state
 * @param {object} params.actions
 * @param {object} params.formatters
 * @param {object} params.constants
 * @param {object} params.helpers
 */
export function buildOverlayViewInputs({ state, actions, formatters, constants, helpers }) {
  return {
    dropdownItems: state.dropdownItems,
    matchesAction: actions.matchesAction,
    setStatusMessage: actions.setStatusMessage,
    jumpList: state.jumpList,
    pathHistory: state.pathHistory,
    scrollDropdownToIndex: actions.scrollDropdownToIndex,
    selectDropdown: actions.selectDropdown,
    removeHistory: actions.removeHistory,
    removeJump: actions.removeJump,
    trapModalTab: actions.trapModalTab,
    searchActive: state.searchActive,
    searchError: state.searchError,
    onSearchKeydown: actions.onSearchKeydown,
    applySearch: actions.applySearch,
    clearSearch: actions.clearSearch,
    sortMenuOpen: state.sortMenuOpen,
    setSort: actions.setSort,
    handleSortMenuKey: actions.handleSortMenuKey,
    aboutOpen: state.aboutOpen,
    openUrl: actions.openUrl,
    ABOUT_URL: constants.ABOUT_URL,
    ABOUT_LICENSE: constants.ABOUT_LICENSE,
    closeAbout: actions.closeAbout,
    deleteConfirmOpen: state.deleteConfirmOpen,
    deleteTargets: state.deleteTargets,
    deleteError: state.deleteError,
    confirmDelete: actions.confirmDelete,
    cancelDelete: actions.cancelDelete,
    pasteConfirmOpen: state.pasteConfirmOpen,
    pasteConflicts: state.pasteConflicts,
    confirmPasteOverwrite: actions.confirmPasteOverwrite,
    confirmPasteSkip: actions.confirmPasteSkip,
    cancelPasteConfirm: actions.cancelPasteConfirm,
    createOpen: state.createOpen,
    createError: state.createError,
    confirmCreate: actions.confirmCreate,
    cancelCreate: actions.cancelCreate,
    jumpUrlOpen: state.jumpUrlOpen,
    confirmJumpUrl: actions.confirmJumpUrl,
    cancelJumpUrl: actions.cancelJumpUrl,
    renameOpen: state.renameOpen,
    renameError: state.renameError,
    confirmRename: actions.confirmRename,
    cancelRename: actions.cancelRename,
    propertiesOpen: state.propertiesOpen,
    propertiesData: state.propertiesData,
    dirStatsInFlight: state.dirStatsInFlight,
    formatSize: formatters.formatSize,
    formatModified: formatters.formatModified,
    saveDirStatsTimeout: actions.saveDirStatsTimeout,
    clearDirStatsCache: actions.clearDirStatsCache,
    retryDirStats: actions.retryDirStats,
    cancelDirStats: actions.cancelDirStats,
    closeProperties: actions.closeProperties,
    autofocus: actions.autofocus,
    zipModalOpen: state.zipModalOpen,
    zipMode: state.zipMode,
    zipTargets: state.zipTargets,
    zipPasswordAttempts: state.zipPasswordAttempts,
    ZIP_PASSWORD_MAX_ATTEMPTS: constants.ZIP_PASSWORD_MAX_ATTEMPTS,
    zipError: state.zipError,
    zipOverwriteConfirmed: state.zipOverwriteConfirmed,
    runZipAction: actions.runZipAction,
    closeZipModal: actions.closeZipModal,
    contextMenuOpen: state.contextMenuOpen,
    contextMenuPos: state.contextMenuPos,
    getContextMenuItems: actions.getContextMenuItems,
    contextMenuIndex: state.contextMenuIndex,
    getSelectableIndex: actions.getSelectableIndex,
    handleContextMenuKey: actions.handleContextMenuKey,
    error: state.error,
    failureModalOpen: state.failureModalOpen,
    failureModalTitle: state.failureModalTitle,
    failureItems: state.failureItems,
    failureMessage: actions.failureMessage,
    closeFailureModal: actions.closeFailureModal,
    t: helpers.t,
  };
}
